/* KOREX · 16 component card specs. Tags: code = real prop · native = native HTML attr · composition = built from props/children · preview-only = forced visual state for the card only · design-only = drawn, not in code API. Fictional sample content. */
(function(){
const h=React.createElement,F=React.Fragment,X=window.KX;
const {Icon,Button,TextField,Textarea,Select,Checkbox,Switch,Badge,Card,Skeleton,Dialog,Menu,Table,Pagination,AlertDialog}=X;const TV=X.preview.ToastView;
const W=(w,el)=>h('div',{style:{width:w,maxWidth:'100%'}},el);
const LONG='경기도 화성시 동탄첨단산업단지 내 2층 규모 제조시설 및 부속 창고 일괄 임대 (크레인 5톤 포함)';
const opt=(a)=>a.map(x=>h('option',{key:x},x));
const B=(p,t)=>h(Button,p,t||'매물 검색');
const S={};
S.Button={name:'Button',group:'KOREX · Component · Actions',description:'주 행동은 녹색 채움(primary), 보조 CTA는 직사각형 녹색 outline, 카테고리·필터는 pill chip. 반경 2px, pill은 chip 전용.',meta:['master/lib/kx-ui.js · Button','variant: primary|secondary|outline|chip|danger|text','size: sm 32|md 40|lg 48','selected → aria-pressed','radius 2 · chip pill'],
sections:[
{title:'Variant',cases:[{id:'primary',label:'primary — 검색 버튼 (observed)',tag:'observed',el:B({variant:'primary'},h(F,null,h(Icon,{name:'kx:search',size:18}),'매물 검색'))},{id:'outline',label:'outline — 직사각형 CTA (observed)',tag:'observed',el:B({variant:'outline'},'상담 신청하기')},{id:'chip',label:'chip — pill 카테고리 (observed)',tag:'observed',el:h(F,null,B({variant:'chip'},'공장'),B({variant:'chip',selected:true},'창고'))},{id:'secondary',label:'secondary',el:B({variant:'secondary'},'취소')},{id:'danger',label:'danger',el:B({variant:'danger'},'매물 삭제')},{id:'text',label:'text',el:B({variant:'text'},h(F,null,'전체 보기',h(Icon,{name:'kx:arrow-right',size:16})))}]},
{title:'Size',cases:[{id:'sm',label:'sm · 32',el:h(F,null,B({size:'sm'}),B({size:'sm',variant:'outline'},'문의'))},{id:'md',label:'md · 40',el:h(F,null,B({}),B({variant:'outline'},'문의'))},{id:'lg',label:'lg · 48',el:h(F,null,B({size:'lg'}),B({size:'lg',variant:'outline'},'문의'))}]},
{title:'State',note:'hover/pressed/focus는 data-preview-state로 고정 표시(미리보기 전용). 실제는 :hover/:active/:focus-visible.',cases:[
 {id:'default',label:'default',el:B({})},{id:'hover',label:'hover',tag:'preview-only',el:h(F,null,B({'data-preview-state':'hover'}),B({variant:'outline','data-preview-state':'hover'},'문의'))},{id:'focus',label:'focus · 2px outline + 2px offset',tag:'preview-only',el:B({'data-preview-state':'focus'})},{id:'pressed',label:'pressed',tag:'preview-only',el:h(F,null,B({'data-preview-state':'pressed'}),B({variant:'outline','data-preview-state':'pressed'},'문의'))},
 {id:'selected',label:'selected (chip)',el:h(F,null,B({variant:'chip',selected:true},'지식산업센터'),B({variant:'chip',selected:true,size:'sm'},'임대'))},{id:'disabled',label:'disabled',tag:'native',el:h(F,null,B({disabled:true}),B({variant:'outline',disabled:true},'문의'))},{id:'loading',label:'loading',el:B({loading:true},'검색 중')},
 {id:'long',label:'긴 문구 · nowrap → 컨테이너에서 줄바꿈 없이 확장',w2:true,el:W(420,h('div',{className:'row'},B({variant:'outline'},'이 매물과 비슷한 조건의 산업용 부동산 알림 받기')))},{id:'on-brand',label:'deep-green 면 위 outline',w2:true,el:h('div',{className:'kx-on-brand',style:{background:'var(--bg-brand)',padding:16,borderRadius:6,display:'flex',gap:8,flexWrap:'wrap'}},B({},'매물 검색'),B({variant:'outline'},'중개사 등록'))}]}],
notApplicable:['empty / error / success: 버튼 자체 상태가 아님 — 폼·토스트에서 표현']};
S.TextField={name:'TextField',group:'KOREX · Component · Inputs',description:'label·description·error가 연결된 입력. 44px 높이, 반경 2px, 회색 테두리.',meta:['label (필수)','description','error → aria-invalid','required','native input attrs'],
sections:[{title:'State',cases:[
 {id:'default',label:'default',el:W(260,h(TextField,{label:'지역',placeholder:'시·군·구 또는 산업단지명'}))},{id:'filled',label:'filled',el:W(260,h(TextField,{label:'지역',defaultValue:'화성시 동탄'}))},{id:'hover',label:'hover',tag:'preview-only',el:W(260,h(TextField,{label:'지역',placeholder:'검색어','data-preview-state':'hover'}))},{id:'focus',label:'focus',tag:'preview-only',el:W(260,h(TextField,{label:'지역',defaultValue:'평택','data-preview-state':'focus'}))},
 {id:'description',label:'description',el:W(260,h(TextField,{label:'전용면적 (㎡)',type:'number',defaultValue:'1650',description:'평 환산: 약 499평'}))},{id:'required',label:'required',el:W(260,h(TextField,{label:'연락처',required:true,type:'tel',placeholder:'010-0000-0000'}))},
 {id:'error',label:'error',el:W(260,h(TextField,{label:'이메일',defaultValue:'agent@korex',error:'올바른 이메일 형식이 아닙니다.'}))},{id:'disabled',label:'disabled',tag:'native',el:W(260,h(TextField,{label:'매물번호',defaultValue:'KX-24-00318',disabled:true}))},
 {id:'success',label:'success (description 문구로 표현)',tag:'composition',el:W(260,h(TextField,{label:'사업자등록번호',defaultValue:'123-45-67890',description:'✓ 확인된 번호입니다.'}))},{id:'long',label:'긴 값·긴 오류',w2:true,el:W(460,h(TextField,{label:'매물 제목',defaultValue:LONG,error:'제목은 40자 이내로 입력해 주세요. 현재 입력된 제목이 너무 길어 목록에서 잘립니다.'}))}]}],
notApplicable:['loading: 입력 자체에는 없음 (검색 버튼 loading 사용)']};
S.Textarea={name:'Textarea',group:'KOREX · Component · Inputs',description:'여러 줄 입력. 최소 104px, 세로 리사이즈.',meta:['TextField와 같은 props','rows 기본 4'],
sections:[{title:'State',cases:[{id:'default',label:'default',el:W(300,h(Textarea,{label:'문의 내용',placeholder:'희망 면적, 입주 시기, 업종을 적어 주세요.'}))},{id:'filled',label:'filled',el:W(300,h(Textarea,{label:'문의 내용',rows:3,defaultValue:'전용 1,000㎡ 이상, 층고 8m 이상 창고를 11월 입주 기준으로 찾고 있습니다.'}))},{id:'focus',label:'focus',tag:'preview-only',el:W(300,h(Textarea,{label:'메모',rows:3,'data-preview-state':'focus'}))},{id:'error',label:'error',el:W(300,h(Textarea,{label:'문의 내용',rows:3,error:'10자 이상 입력해 주세요.',defaultValue:'창고 문의'}))},{id:'disabled',label:'disabled',tag:'native',el:W(300,h(Textarea,{label:'관리자 메모',rows:3,disabled:true,defaultValue:'검수 완료 후 수정할 수 없습니다.'}))},{id:'long',label:'긴 문구',el:W(300,h(Textarea,{label:'매물 설명',rows:4,defaultValue:LONG+'. 진입도로 12m, 대형 트레일러 회차 가능, 3상 전력 500kW 인입 완료, 사무동 2층 별도.'}))}]}]};
S.Select={name:'Select',group:'KOREX · Component · Inputs',description:'native select + KOREX 화살표. 검색 패널의 매물유형/거래유형 선택에 사용.',meta:['TextField props + children <option>'],
sections:[{title:'State',cases:[{id:'default',label:'default',el:W(240,h(Select,{label:'매물 유형'},opt(['전체','공장','창고','사무실','상가','토지'])))},{id:'selected',label:'selected value',el:W(240,h(Select,{label:'거래 유형',defaultValue:'임대'},opt(['매매','임대','전대'])))},{id:'focus',label:'focus',tag:'preview-only',el:W(240,h(Select,{label:'지역','data-preview-state':'focus'},opt(['경기 남부','경기 북부'])))},{id:'error',label:'error',el:W(240,h(Select,{label:'매물 유형',error:'유형을 선택해 주세요.',defaultValue:''},h('option',{value:''},'선택'),opt(['공장','창고'])))},{id:'disabled',label:'disabled',tag:'native',el:W(240,h(Select,{label:'담당 중개사',disabled:true},opt(['자동 배정'])))},{id:'long',label:'긴 옵션',el:W(240,h(Select,{label:'산업단지'},opt(['동탄첨단산업단지 (경기도 화성시 동탄면 일원)','평택 포승국가산업단지'])))}]}]};
S.Checkbox={name:'Checkbox',group:'KOREX · Component · Inputs',description:'필터 조건 선택. accent-color = action green.',meta:['label','native checkbox attrs'],
sections:[{title:'State',cases:[{id:'unchecked',label:'unchecked',el:h(Checkbox,{label:'주차 가능'})},{id:'checked',label:'checked (selected)',el:h(Checkbox,{label:'화물용 엘리베이터',defaultChecked:true})},{id:'focus',label:'focus',tag:'preview-only',el:h(Checkbox,{label:'즉시 입주','data-preview-state':'focus'})},{id:'disabled',label:'disabled',tag:'native',el:h(F,null,h(Checkbox,{label:'신축',disabled:true}),h(Checkbox,{label:'검증 매물',disabled:true,defaultChecked:true}))},{id:'long',label:'긴 문구',el:W(280,h(Checkbox,{label:'개인정보 수집·이용 및 중개사 연락처 제공에 동의합니다 (필수)'}))}]}],notApplicable:['indeterminate / error: 현재 API 없음']};
S.Switch={name:'Switch',group:'KOREX · Component · Inputs',description:'즉시 적용되는 설정. role="switch".',meta:['label','checked/defaultChecked/disabled'],
sections:[{title:'State',cases:[{id:'off',label:'off',el:h(Switch,{label:'신규 매물 알림'})},{id:'on',label:'on (selected)',el:h(Switch,{label:'관심 매물 가격 변동 알림',defaultChecked:true})},{id:'focus',label:'focus',tag:'preview-only',el:h(Switch,{label:'문자 알림','data-preview-state':'focus'})},{id:'disabled',label:'disabled',tag:'native',el:h(F,null,h(Switch,{label:'광고 수신',disabled:true}),h(Switch,{label:'필수 알림',disabled:true,defaultChecked:true}))},{id:'long',label:'긴 문구',el:W(280,h(Switch,{label:'관심 지역에 조건과 일치하는 매물이 등록되면 이메일과 문자로 알림 받기'}))}]}]};
S.Badge={name:'Badge',group:'KOREX · Component · Display',description:'매물 상태 표기. 반경 2px 사각 라벨 — pill은 카테고리 chip(Button)만.',meta:['tone: neutral|success|warning|error|info|brand'],
sections:[{title:'Tone',cases:[{id:'neutral',label:'neutral',el:h(Badge,null,'임대')},{id:'success',label:'success',el:h(Badge,{tone:'success'},'검증 완료')},{id:'warning',label:'warning',el:h(Badge,{tone:'warning'},'가격 조정')},{id:'error',label:'error',el:h(Badge,{tone:'error'},'거래 종료')},{id:'info',label:'info',el:h(Badge,{tone:'info'},'신규')},{id:'brand',label:'brand (KOREX 추천)',el:h(Badge,{tone:'brand'},'KOREX 추천')},{id:'icon',label:'icon + text',tag:'composition',el:h(Badge,{tone:'success'},h(Icon,{name:'kx:shield',size:14}),'실사 확인')},{id:'long',label:'긴 문구',el:W(200,h(Badge,{tone:'warning'},'소유자 확인 서류 보완 요청'))}]}]};
S.Card={name:'Card',group:'KOREX · Component · Display',description:'흰 면 + 회색 1px 테두리, 반경 6. tone=brand는 녹색 통계 패널(observed), tone=mint는 연민트 강조면.',meta:['title','footer','tone: default|brand|mint','children'],
sections:[{title:'Tone',cases:[{id:'default',label:'default',el:W(280,h(Card,{title:'관심 매물',footer:'3일 전 업데이트'},h('div',{className:'kpi'},'12')))},{id:'brand',label:'brand — 녹색 통계 패널 (observed)',tag:'observed',el:W(280,h(Card,{title:'이번 주 신규 매물',tone:'brand',footer:'경기 남부 기준'},h('div',{className:'kpi'},'148'),h('span',{className:'delta up'},'+12 지난주 대비')))},{id:'mint',label:'mint',el:W(280,h(Card,{title:'맞춤 추천',tone:'mint'},h('p',null,'조건 3개에 맞는 매물 7건')))}]},
{title:'Composition',cases:[{id:'listing',label:'listing — 사진 좌 / 글 우 (observed)',tag:'observed',wide:true,el:h('div',{style:{width:'100%'}},h('div',{className:'lst'},h('div',{className:'ph'},'매물 사진'),h('div',{className:'stack g8'},h('div',{className:'row',style:{gap:6}},h(Badge,{tone:'success'},'검증 완료'),h(Badge,null,'임대')),h('h3',null,'화성 동탄 제조공장 1,650㎡'),h('span',{className:'muted'},'경기 화성시 · 층고 9m · 3상 500kW'),h('span',{className:'price'},'보증금 2억 / 월 1,450만')),h('div',{className:'lst-act'},h('button',{className:'heart',type:'button','aria-pressed':'false','aria-label':'관심 매물 저장'},h(Icon,{name:'kx:heart'})))))},
{id:'loading',label:'loading',el:W(280,h(Card,{'aria-busy':'true'},h(Skeleton,{height:14,width:'40%'}),h(Skeleton,{height:32,width:'60%'})))},{id:'empty',label:'empty',el:W(280,h(Card,{title:'관심 매물'},h('p',{className:'muted'},'저장한 매물이 없습니다. 목록의 ♡로 저장하세요.')))},{id:'missing',label:'누락 데이터',el:W(280,h(Card,{title:'관리비'},h('div',{className:'kpi miss'},'—'),h('span',{className:'muted'},'중개사 미입력')))},{id:'long',label:'긴 제목',el:W(280,h(Card,{title:LONG},h('span',{className:'muted'},'제목은 줄바꿈되고 잘리지 않습니다.')))}]}]};
S.Skeleton={name:'Skeleton',group:'KOREX · Component · Feedback',description:'로딩 자리 표시. 회색 쉬머, reduced-motion 시 정지.',meta:['width','height','circle'],
sections:[{title:'Shape',cases:[{id:'line',label:'line',el:W(240,h('div',{className:'stack g8'},h(Skeleton,{height:14}),h(Skeleton,{height:14,width:'70%'})))},{id:'circle',label:'circle',el:h(Skeleton,{width:40,height:40,circle:true})},{id:'listing',label:'listing row',tag:'composition',wide:true,el:h('div',{className:'lst',style:{width:'100%'}},h(Skeleton,{height:120}),h('div',{className:'stack g8'},h(Skeleton,{height:18,width:'50%'}),h(Skeleton,{height:14,width:'70%'}),h(Skeleton,{height:24,width:'40%'})),h(Skeleton,{width:40,height:40}))}]}]};
S.Icon={name:'Icon',group:'KOREX · Component · Display',description:'KOREX 선형 아이콘 (자체 제작, derived-extension). 연민트 사각 타일(observed)과 outline heart(observed)를 포함.',meta:['name: kx:*','size (기본 20)','label → role=img'],
sections:[{title:'Size & usage',cases:[{id:'sizes',label:'16 / 20 / 24',el:h(F,null,h(Icon,{name:'kx:search',size:16}),h(Icon,{name:'kx:search',size:20}),h(Icon,{name:'kx:search',size:24}))},{id:'tile',label:'연민트 사각 타일 (observed)',tag:'observed',el:h(F,null,['kx:factory','kx:warehouse','kx:building'].map(n=>h('span',{key:n,className:'kx-icon-tile'},h(Icon,{name:n,size:24}))))},{id:'heart',label:'outline heart → 저장됨 (observed)',tag:'observed',el:h(F,null,h('button',{className:'heart',type:'button','aria-pressed':'false','aria-label':'저장'},h(Icon,{name:'kx:heart'})),h('button',{className:'heart',type:'button','aria-pressed':'true','aria-label':'저장됨'},h(Icon,{name:'kx:heart-fill'})))},{id:'labelled',label:'label → role="img"',el:h(Icon,{name:'kx:shield',label:'검증 매물',size:24})},{id:'unknown',label:'없는 이름 → null',el:h('span',{className:'muted'},'kx:none → ',h(Icon,{name:'kx:none'}),'(렌더 없음)')}]}]};
S.Dialog={name:'Dialog',group:'KOREX · Component · Overlay',description:'모달. 흰 면, 반경 6, 딥그린 오버레이. focus trap + Esc.',meta:['title','description','footer','size: sm|md|lg','open/defaultOpen/onOpenChange','inline (preview-only)'],
sections:[{title:'Size',cases:[{id:'md',label:'md · 상담 신청',wide:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:460}},h(Dialog,{inline:true,title:'상담 신청',description:'담당 중개사가 1영업일 안에 연락드립니다.',footer:h(F,null,h(Button,{variant:'secondary'},'취소'),h(Button,null,'신청하기'))},h('div',{className:'stack g16'},h(TextField,{label:'이름',required:true}),h(TextField,{label:'연락처',type:'tel',required:true}))))},
{id:'sm',label:'sm',w2:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:260}},h(Dialog,{inline:true,size:'sm',title:'지도 범위 저장',footer:h(Button,null,'저장')},h(TextField,{label:'이름',defaultValue:'동탄 산단 반경 5km'})))},{id:'long',label:'긴 제목',w2:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:260}},h(Dialog,{inline:true,size:'sm',title:LONG,footer:h(Button,{variant:'secondary'},'닫기')},h('p',{className:'muted'},'제목은 줄바꿈됩니다.')))},{id:'focus-close',label:'close focus',tag:'preview-only',el:h('button',{className:'kx-dialog-close','data-preview-state':'focus','aria-label':'닫기'},h(Icon,{name:'kx:close'}))}]}]};
const mItems=[{id:'save',label:'관심 매물 저장',onSelect(){}},{id:'share',label:'링크 복사',onSelect(){}},{id:'report',label:'허위 매물 신고',disabled:true},{id:'hide',label:'이 매물 숨기기',danger:true,separatorBefore:true,onSelect(){}}];
S.Menu={name:'Menu',group:'KOREX · Component · Overlay',description:'행 더보기 메뉴. 강조 항목은 연민트.',meta:['trigger','label','items[] {id,label,onSelect,disabled,danger,separatorBefore}','align: start|center|end'],
sections:[{title:'State',cases:[{id:'trigger',label:'trigger (클릭해 열기)',el:h(Menu,{label:'매물 작업',trigger:h(Button,{variant:'secondary',size:'sm','aria-label':'더보기'},h(Icon,{name:'kx:more'})),items:mItems})},{id:'open',label:'open · highlighted · disabled · danger',el:h(Menu,{inline:true,label:'매물 작업',items:mItems,highlightedId:'share'})},{id:'long',label:'긴 항목',el:W(240,h(Menu,{inline:true,label:'정렬',items:[{id:'a',label:'최근 등록순'},{id:'b',label:'전용면적 넓은순 (공용 제외, 도면 기준 면적)'}]}))}]}]};
const rows=[{id:'KX-318',t:'화성 동탄 제조공장',type:'공장',area:1650,price:14500000,st:'검증 완료'},{id:'KX-322',t:'평택 포승 물류창고',type:'창고',area:3300,price:21000000,st:'신규'},{id:'KX-327',t:'성수 지식산업센터 8층',type:'사무실',area:198,price:null,st:'가격 조정'},{id:'KX-331',t:'김포 양촌 소형 창고',type:'창고',area:495,price:3800000,st:'거래 종료'}];
const TN={'검증 완료':'success','신규':'info','가격 조정':'warning','거래 종료':'error'};
const cols=[{id:'t',header:'매물',cell:r=>r.t,sortValue:r=>r.t},{id:'type',header:'유형',cell:r=>r.type},{id:'area',header:'전용면적',cell:r=>r.area.toLocaleString('ko-KR')+'㎡',sortValue:r=>r.area,align:'right'},{id:'price',header:'월 임대료',cell:r=>r.price==null?h('span',{className:'miss'},'협의'):'₩'+r.price.toLocaleString('ko-KR'),sortValue:r=>r.price,align:'right'},{id:'st',header:'상태',cell:r=>h(Badge,{tone:TN[r.st]},r.st)}];
S.Table={name:'Table',group:'KOREX · Component · Data',description:'딥그린 2px 상단 룰 + 회색 헤더. 정렬·페이지·가상 스크롤·loading/error/empty 내장.',meta:['caption','columns[] {id,header,cell,sortValue,align}','rows · rowKey','sort/defaultSort/onSortChange','loading · error · emptyMessage','pagination {pageSize}','virtualization'],
sections:[{title:'State',cases:[{id:'default',label:'default · sorted',wide:true,el:h(Table,{caption:'등록 매물',columns:cols,rows,rowKey:r=>r.id,defaultSort:{columnId:'area',direction:'descending'},minWidth:640})},{id:'paginated',label:'pagination',wide:true,el:h(Table,{caption:'등록 매물 (페이지)',columns:cols,rows:[...rows,...rows.map(r=>({...r,id:r.id+'b'}))],rowKey:r=>r.id,pagination:{pageSize:3},minWidth:640})},
{id:'loading',label:'loading',w2:true,el:h(Table,{caption:'등록 매물',columns:cols,rows:[],rowKey:r=>r.id,loading:true,minWidth:480})},{id:'error',label:'error',w2:true,el:h(Table,{caption:'등록 매물',columns:cols,rows:[],rowKey:r=>r.id,error:'목록을 불러오지 못했습니다. 다시 시도해 주세요.',minWidth:480})},{id:'empty',label:'empty',w2:true,el:h(Table,{caption:'등록 매물',columns:cols,rows:[],rowKey:r=>r.id,emptyMessage:'조건에 맞는 매물이 없습니다.',minWidth:480})},{id:'long',label:'긴 문구·누락(협의)',w2:true,el:h(Table,{caption:'등록 매물',columns:cols.slice(0,4),rows:[{...rows[2],t:LONG}],rowKey:r=>r.id,minWidth:480})},{id:'sort-focus',label:'sort focus',tag:'preview-only',el:h('button',{className:'kx-table-sort','data-preview-state':'focus'},'전용면적 ↕')}]}]};
function PgDemo(p){const [pg,setPg]=React.useState(p.page||1);return h(Pagination,{...p,page:pg,onPageChange:setPg})}
S.Pagination={name:'Pagination',group:'KOREX · Component · Data',description:'번호형 페이지. 현재 페이지 = 딥그린 채움(selected).',meta:['page','pageCount','onPageChange','disabled','label'],
sections:[{title:'State',cases:[{id:'default',label:'default (클릭 가능)',w2:true,el:h(PgDemo,{page:3,pageCount:12})},{id:'first',label:'first page',el:h(PgDemo,{page:1,pageCount:5})},{id:'hover',label:'hover',tag:'preview-only',el:h(Pagination,{page:2,pageCount:5,onPageChange(){},previewState:'hover'})},{id:'focus',label:'focus',tag:'preview-only',el:h(Pagination,{page:2,pageCount:5,onPageChange(){},previewState:'focus'})},{id:'disabled',label:'disabled',el:h(Pagination,{page:2,pageCount:5,onPageChange(){},disabled:true})},{id:'single',label:'1 page',el:h(Pagination,{page:1,pageCount:1,onPageChange(){}})}]}]};
function ToastDemo(){const t=X.useToast();return h('div',{className:'row'},h(Button,{size:'sm',onClick:()=>t.notify({tone:'success',title:'관심 매물에 저장했습니다.'})},'success 띄우기'),h(Button,{size:'sm',variant:'secondary',onClick:()=>t.notify({tone:'error',title:'상담 신청을 보내지 못했습니다.',description:'잠시 후 다시 시도해 주세요.'})},'error 띄우기'))}
const T=(p)=>h('ol',{style:{listStyle:'none',margin:0,padding:0,width:'100%'}},h(TV,{onClose(){},...p}));
S.Toast={name:'Toast',group:'KOREX · Component · Feedback',description:'왼쪽 4px 상태 룰 + 사각 아이콘 타일(반경 4). 최대 3개, 기본 5초.',meta:['ToastProvider {duration,label}','useToast().notify({title,description,tone,action,duration})','tone: success|warning|error|info'],
sections:[{title:'Tone',cases:[{id:'success',label:'success',w2:true,el:T({tone:'success',title:'관심 매물에 저장했습니다.',description:'마이페이지 › 관심 매물에서 볼 수 있습니다.'})},{id:'info',label:'info',w2:true,el:T({tone:'info',title:'새 매물 3건이 등록되었습니다.'})},{id:'warning',label:'warning',w2:true,el:T({tone:'warning',title:'가격이 조정된 매물이 있습니다.',action:{label:'확인하기',altText:'가격 조정 매물 확인',onClick(){}}})},{id:'error',label:'error',w2:true,el:T({tone:'error',title:'상담 신청을 보내지 못했습니다.',description:'네트워크 상태를 확인해 주세요.'})},{id:'long',label:'긴 문구',w2:true,el:T({tone:'info',title:LONG,description:'설명도 줄바꿈되며 닫기 버튼은 고정 위치를 유지합니다.'})},{id:'close-focus',label:'close focus',tag:'preview-only',w2:true,el:T({tone:'success',title:'저장했습니다.',previewState:'focus'})},{id:'live',label:'live provider',tag:'composition',wide:true,el:h(X.ToastProvider,null,h(ToastDemo))}]}]};
S.AlertDialog={name:'AlertDialog',group:'KOREX · Component · Overlay',description:'되돌릴 수 없는 작업 확인. pending/error 흐름 내장.',meta:['title','description','confirmLabel','cancelLabel','danger','onConfirm (async)','errorMessage','previewState (preview-only)'],
sections:[{title:'State',cases:[{id:'default',label:'danger · default',w2:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:280}},h(AlertDialog,{inline:true,danger:true,title:'매물을 삭제할까요?',description:'KX-318 매물과 사진 12장이 삭제되며 복원할 수 없습니다.',confirmLabel:'삭제',onConfirm(){}}))},{id:'pending',label:'pending',w2:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:300}},h(AlertDialog,{inline:true,danger:true,title:'매물을 삭제할까요?',description:'복원할 수 없습니다.',confirmLabel:'삭제',previewState:'pending',onConfirm(){}}))},{id:'error',label:'error',w2:true,el:h('div',{className:'kx-stage',style:{width:'100%',height:320}},h(AlertDialog,{inline:true,title:'거래 완료로 변경할까요?',description:'목록에서 “거래 종료”로 표시됩니다.',confirmLabel:'변경',previewState:'error',onConfirm(){}}))},{id:'trigger',label:'trigger (실제 열기)',el:h(AlertDialog,{trigger:h(Button,{variant:'danger',size:'sm'},'삭제'),danger:true,title:'매물을 삭제할까요?',description:'복원할 수 없습니다.',confirmLabel:'삭제',onConfirm:()=>new Promise(r=>setTimeout(r,800))})}]}]};
window.KX_SPECS=S;
})();
