import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM} from 'jsdom';
const root='src/systems/HYNIX_V1/preview/';
function open(page,query=''){const dom=new JSDOM(readFileSync(root+page+'.html','utf8'),{url:'https://demo.test/'+page+'.html'+query,runScripts:'outside-only'});dom.window.eval(readFileSync(root+'industrial.js','utf8'));return dom;}
test('equipment filters compose with search and preserve missing data',()=>{const d=open('sub'),doc=d.window.document;doc.querySelector('[data-filter=offline]').click();assert.match(doc.querySelector('#result-count').textContent,/1 of 6/);assert.match(doc.querySelector('#results').textContent,/Module 06/);assert.equal(doc.querySelectorAll('td')[3].textContent,'—');const s=doc.querySelector('#search');s.value='unmatched';s.dispatchEvent(new d.window.Event('input'));assert.match(doc.querySelector('#results').textContent,/No equipment/);d.window.close();});
test('offline detail disables commands and keyboard tabs expose correct panel',()=>{const d=open('detail','?device=06'),doc=d.window.document;assert.equal(doc.querySelector('#command button').disabled,true);doc.querySelector('#tab-0').dispatchEvent(new d.window.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(doc.querySelector('#tab-1').getAttribute('aria-selected'),'true');assert.equal(doc.querySelector('#panel-1').hidden,false);assert.equal(doc.querySelector('#panel-0').hidden,true);assert.match(doc.querySelector('#panel-1').textContent,/Telemetry unavailable/);d.window.close();});
test('chart time window changes actual plot and accessible description',()=>{const d=open('index'),doc=d.window.document,before=doc.querySelector('polyline').getAttribute('points');doc.querySelector('[data-window="1h"]').click();assert.notEqual(doc.querySelector('polyline').getAttribute('points'),before);assert.match(doc.querySelector('svg').getAttribute('aria-label'),/1h/);d.window.close();});
test('meter zero is a valid value while unavailable has no meter role',()=>{const d=open('components'),doc=d.window.document;assert.ok(doc.querySelector('[role=meter][aria-valuenow="0"]'));assert.equal([...doc.querySelectorAll('[role=meter]')].some(e=>e.getAttribute('aria-valuenow')==='null'),false);assert.equal(doc.querySelectorAll('.spec').length,17);d.window.close();});
test('detail event scope and local review preserve equipment state',()=>{const d=open('detail','?device=05'),doc=d.window.document;assert.match(doc.querySelector('#event-results').textContent,/Module 05/);assert.doesNotMatch(doc.querySelector('#event-results').textContent,/Module 06/);doc.querySelector('[data-event-scope=all]').click();assert.match(doc.querySelector('#event-results').textContent,/Module 06/);doc.querySelector('#review-save').click();assert.equal(doc.activeElement.id,'review-note');const note=doc.querySelector('#review-note');note.value='온도 기록 검토';note.dispatchEvent(new d.window.Event('input'));doc.querySelector('#review-save').click();assert.match(doc.querySelector('#review-result').textContent,/실제 경보·장비 상태는 변경되지/);assert.match(doc.querySelector('#panel-0').textContent,/Critical/);note.value='수정';note.dispatchEvent(new d.window.Event('input'));assert.match(doc.querySelector('#review-result').textContent,/다시 검토/);doc.querySelector('#review-reset').click();assert.equal(note.value,'');d.window.close();});
test('event absence is explicit and does not imply healthy equipment',()=>{const d=open('detail','?device=01');assert.match(d.window.document.querySelector('#event-results').textContent,/정상 상태를 보증하지/);d.window.close();});
