/* DEW editorial library — 11 reusable parts + 3 example pages (EditorialHome · ArticleList · StoryDetail). window.DEW_ED. Fictional data only. Photos are placeholders (no drawn imagery). */
(function(){
const h=React.createElement,F=React.Fragment,D=window.DEW;const {Icon,Button,Badge,Select,Pagination,Skeleton}=D;
const Photo=({label,ratio='4/3',tone})=>h('div',{className:'dew-photo'+(tone?' dew-photo--'+tone:''),style:{aspectRatio:ratio}},h('span',null,'PHOTO · ',label||ratio));
function EditorialHeader({issue='No. 27 · Autumn 2026',tagline='Editorial Webzine',title='DEW',compact}){return h('header',{className:'ed-header'},h('div',{className:'ed-header-top'},h('span',null,issue),h('span',null,tagline)),compact?h('span',{className:'dew-wordmark',style:{font:'400 48px/1 var(--dew-font-display)'}},title):h('h1',{className:'ed-header-mast'},title))}
function CategoryNav({items=[],current,onSelect,label='카테고리'}){return h('nav',{className:'ed-catnav','aria-label':label},items.map(it=>h('a',{key:it,href:'#','aria-current':it===current?'page':undefined,onClick:e=>{e.preventDefault();onSelect&&onSelect(it)}},it)))}
function ArticleMeta({author,photographer,date,read,category}){const x=[category&&h('b',{key:'c'},category),h('span',{key:'a'},author?'글 '+author:h('span',{className:'dew-miss'},'필자 미지정')),photographer&&h('span',{key:'p'},'사진 '+photographer),date&&h('span',{key:'d'},date),read&&h('span',{key:'r'},read)].filter(Boolean);return h('div',{className:'ed-meta'},x)}
function ImageCaption({caption,credit}){if(!caption&&!credit)return null;return h('figcaption',{className:'ed-caption'},h('span',null,caption||h('span',{className:'dew-miss'},'캡션 없음')),credit&&h('b',null,'© '+credit))}
function MediaCard({label,ratio='4/3',tone,kind,caption,credit}){return h('figure',{className:'ed-media'},h('div',{className:'ed-media-frame'},h(Photo,{label,ratio,tone}),kind&&h('span',{className:'ed-media-badge','aria-label':kind==='video'?'영상':'갤러리'},h(Icon,{name:kind==='video'?'eva:arrow-ios-forward-fill':'solar:square-double-alt-arrow-right-bold',size:20}))),h(ImageCaption,{caption,credit}))}
function StoryCard({story,layout='stack',loading}){if(loading)return h('div',{className:'ed-card','aria-hidden':true},h(Skeleton,{height:220}),h(Skeleton,{height:12,width:'30%'}),h(Skeleton,{height:24}),h(Skeleton,{height:12,width:'50%'}));const s=story||{};return h('a',{href:'#',className:'ed-card'+(layout==='row'?' ed-card--row':'')},h(Photo,{label:s.photo,ratio:s.ratio||'4/3',tone:s.tone}),h('div',{style:{display:'grid',gap:10,minWidth:0}},h('span',{className:'dew-overline'+(s.featured?' dew-overline--red':'')},s.category||'STORY'),h('h3',null,s.title||h('span',{className:'dew-miss'},'제목 없음')),s.dek&&h('p',null,s.dek),h(ArticleMeta,{author:s.author,read:s.read})))}
function EditorialGrid({children,asymmetric=true}){return h('div',{className:'ed-grid'+(asymmetric?' ed-grid--asym':'')},children)}
function FeatureStory({story,reverse}){const s=story;return h('article',{className:'ed-feature'+(reverse?' ed-feature--reverse':'')},h(MediaCard,{label:'COVER 16:10',ratio:'16/10',tone:'dark',caption:s.caption,credit:s.photographer}),h('div',{className:'ed-feature-copy'},h('span',{className:'dew-overline dew-overline--red'},s.category),h('h2',null,s.title),h('p',{className:'dew-lead',style:{margin:0}},s.dek),h(ArticleMeta,{author:s.author,photographer:s.photographer,read:s.read}),h('div',null,h(Button,{variant:'text'},'READ STORY'))))}
function QuoteBlock({quote,cite}){return h('blockquote',{className:'ed-quote'},h('p',null,'“',quote,'”'),cite&&h('footer',null,'— ',cite))}
function EditorialCTA({title='매주 목요일, 한 편의 긴 글',body='광고 없는 뉴스레터. 언제든 해지할 수 있습니다.',tone='dark',state='default'}){const [st,setSt]=React.useState(state);const [v,setV]=React.useState('');const bad=st==='error';return h('section',{className:'ed-cta'+(tone==='light'?' ed-cta--light':''),'aria-label':'뉴스레터'},h('div',null,h('span',{className:'dew-overline',style:{color:'inherit'}},'NEWSLETTER'),h('h2',null,st==='success'?'구독해 주셔서 감사합니다':title),h('p',null,st==='success'?'확인 메일을 보냈습니다.':body)),st==='success'?h('div',null,h(Badge,{tone:'success'},'구독 완료')):h('form',{noValidate:true,onSubmit:e=>{e.preventDefault();setSt(/.+@.+\..+/.test(v)?'success':'error')}},h('div',{className:'dew-field'},h('label',{htmlFor:'ed-nl-'+tone},'이메일'),h('input',{id:'ed-nl-'+tone,className:'dew-input',type:'email',value:v,onChange:e=>setV(e.target.value),placeholder:'reader@example.com','aria-invalid':bad||undefined,'aria-describedby':bad?'ed-nl-err-'+tone:undefined}),bad&&h('p',{id:'ed-nl-err-'+tone,className:'dew-error',style:{color:tone==='light'?undefined:'#FF8A80'}},'이메일 형식을 확인하세요.')),h(Button,{type:'submit'},'구독하기')))}
function Footer(){const col=(t,l)=>h('div',null,h('h4',null,t),h('ul',null,l.map(x=>h('li',{key:x},h('a',{href:'#'},x)))));return h('footer',{className:'ed-footer'},h('div',{style:{display:'grid',gap:12,alignContent:'start'}},h('span',{className:'dew-wordmark'},'DEW'),h('p',{className:'dew-small dew-muted',style:{margin:0,maxWidth:'32ch'}},'도시와 사람, 책과 음악에 관한 긴 글을 싣는 가상의 웹진.')),col('Sections',['Features','Essay','Interview','Review']),col('Magazine',['Archive','Contributors','About']),col('Follow',['Newsletter','RSS','Contact']),h('div',{className:'ed-footer-legal'},h('span',null,'© 2026 DEW · 가상 데이터 · 파생 UI kit'),h('span',null,'사진 자리표시 · 실제 이미지 미포함')))}
/* data */
const CATS=['All','Features','Essay','Interview','Review','Archive'];
const COVER={category:'COVER STORY',title:'골목 끝, 불 켜진 서점',dek:'오래된 동네의 서점들은 어떻게 저녁을 맞이하는가. 세 곳의 책방 주인과 보낸 가을 오후.',author:'한지우',photographer:'오하람',read:'12분',caption:'망원동의 한 책방, 오후 5시 40분'};
const STORIES=[{category:'ESSAY',title:'종이의 촉감에 대하여',dek:'손끝으로 읽는 책에 관한 짧은 에세이.',author:'정민',read:'6분',ratio:'4/5',tone:'light'},{category:'INTERVIEW',title:'작은 출판사의 다섯 번째 책',dek:'1인 출판사 대표와 나눈 대화.',author:'이도현',read:'9분',ratio:'4/3',tone:'mid'},{category:'REVIEW',title:'가을 음반 다섯 장',author:'박세린',read:'5분',ratio:'1/1'},{category:'FEATURES',title:'2026 가을호 특집 — 도시의 오래된 골목과 새로 문을 연 작은 서점들을 따라 걷는 아주 긴 산책의 기록',dek:'긴 제목 · 줄바꿈 검증용 사례.',author:'한지우',read:'18분',ratio:'4/3',tone:'dark',featured:true},{category:'ESSAY',title:'밤의 도서관',author:null,read:'4분',ratio:'4/5',tone:'light'},{category:'REVIEW',title:'오래된 극장의 마지막 상영',dek:'필자·사진 누락 사례.',author:'이도현',read:'7분',ratio:'4/3'}];
/* pages */
function EditorialHome(){const [c,setC]=React.useState('All');return h('div',{className:'dew-container',style:{display:'grid',gap:48,paddingBottom:24}},h('div',{'data-case':'header','data-tag':'observed'},h(EditorialHeader),h(CategoryNav,{items:CATS,current:c,onSelect:setC})),h('div',{'data-case':'feature','data-tag':'observed'},h(FeatureStory,{story:COVER})),h('section',{'data-case':'grid','data-tag':'derived',style:{display:'grid',gap:20}},h('h2',{className:'dew-h2',style:{borderTop:'var(--dew-rule-heavy)',paddingTop:12,margin:0}},'This issue'),h(EditorialGrid,null,STORIES.slice(0,3).map(s=>h(StoryCard,{key:s.title,story:s})))),h('div',{'data-case':'quote','data-tag':'derived'},h(QuoteBlock,{quote:'책방의 불은 손님이 아니라 동네를 위해 켜 둡니다.',cite:'책방 주인 인터뷰 중'})),h('section',{'data-case':'media','data-tag':'derived',className:'ed-grid'},h('div',{style:{gridColumn:'span 7'}},h(MediaCard,{label:'GALLERY 3:2',ratio:'3/2',tone:'mid',kind:'gallery',caption:'가을호 사진 12장',credit:'오하람'})),h('div',{style:{gridColumn:'span 5'}},h(MediaCard,{label:'VIDEO 4:5',ratio:'4/5',kind:'video',caption:'책방의 하루 · 3분'}))),h('div',{'data-case':'cta','data-tag':'derived'},h(EditorialCTA)),h('div',{'data-case':'footer','data-tag':'derived'},h(Footer)))}
function ArticleList(){const [c,setC]=React.useState('All');const [st,setSt]=React.useState('default');const [p,setP]=React.useState(1);const list=c==='All'?STORIES:STORIES.filter(s=>s.category===c.toUpperCase());return h('div',{className:'dew-container',style:{display:'grid',gap:32,paddingBottom:24}},h('div',{'data-case':'list-header','data-tag':'derived'},h(EditorialHeader,{compact:true,tagline:'Archive'}),h(CategoryNav,{items:CATS,current:c,onSelect:setC})),h('div',{'data-case':'list-tools','data-tag':'code',style:{display:'flex',gap:16,alignItems:'flex-end',flexWrap:'wrap',justifyContent:'space-between'}},h('div',null,h('span',{className:'dew-overline'},'ARTICLES'),h('h1',{className:'dew-h1',style:{margin:'8px 0 0'}},c==='All'?'모든 기사':c)),h('div',{style:{minWidth:200}},h(Select,{label:'미리보기 상태',value:st,onChange:e=>setSt(e.target.value)},h('option',{value:'default'},'default'),h('option',{value:'loading'},'loading'),h('option',{value:'empty'},'empty')))),h('div',{'data-case':'list-rows','data-tag':'derived',style:{borderTop:'var(--dew-rule-heavy)'}},st==='loading'?[0,1,2].map(i=>h('div',{key:i,style:{padding:'20px 0',borderBottom:'var(--dew-rule-hair)'}},h(StoryCard,{loading:true}))):(st==='empty'||!list.length)?h('div',{style:{padding:'64px 0',display:'grid',gap:12,justifyItems:'start'}},h('span',{className:'dew-overline'},'NO RESULTS'),h('h2',{className:'dew-h2',style:{margin:0}},'이 카테고리에는 아직 기사가 없습니다'),h(Button,{variant:'secondary',onClick:()=>{setC('All');setSt('default')}},'모든 기사 보기')):list.map(s=>h(StoryCard,{key:s.title,story:s,layout:'row'}))),h('div',{'data-case':'list-pagination','data-tag':'code',style:{display:'flex',justifyContent:'center'}},h(Pagination,{page:p,pageCount:6,onPageChange:setP})),h(Footer))}
function StoryDetail(){return h('div',{className:'dew-container',style:{display:'grid',gap:40,paddingBottom:24}},h('div',{'data-case':'story-header','data-tag':'derived'},h(EditorialHeader,{compact:true,tagline:'Features'}),h(CategoryNav,{items:CATS,current:'Features'})),h('header',{'data-case':'story-title','data-tag':'observed',style:{display:'grid',gap:16,maxWidth:980}},h('span',{className:'dew-overline dew-overline--red'},COVER.category),h('h1',{className:'dew-display',style:{margin:0,overflowWrap:'anywhere'}},COVER.title),h('p',{className:'dew-lead',style:{margin:0,maxWidth:'60ch'}},COVER.dek),h(ArticleMeta,{category:'FEATURES',author:COVER.author,photographer:COVER.photographer,date:'2026.09.25',read:COVER.read})),h('div',{'data-case':'story-hero','data-tag':'observed'},h(MediaCard,{label:'FULL BLEED 21:9',ratio:'21/9',tone:'dark',caption:COVER.caption,credit:COVER.photographer})),h('div',{className:'ed-article','data-case':'story-body','data-tag':'derived'},h('div',{className:'ed-article-body'},h('p',null,'해가 기울면 골목의 간판들이 하나둘 켜진다. 서점의 불은 조금 늦게, 그러나 가장 오래 켜져 있다. 책방 주인은 저녁 손님보다 지나가는 이웃을 위해 불을 켠다고 말했다.'),h('p',null,'세 곳의 책방은 규모도, 서가의 성격도 다르다. 한 곳은 시집만 두고, 다른 한 곳은 동네 사람들이 맡긴 헌책을 판다. 마지막 한 곳은 문을 연 지 석 달이 되었다.'),h(QuoteBlock,{quote:'오래 머무는 손님이 많을수록 책은 덜 팔려요. 그래도 괜찮습니다.',cite:'시집 서점 주인'}),h(MediaCard,{label:'INLINE 3:2',ratio:'3/2',tone:'light',caption:null,credit:null}),h('p',null,'이 기사는 가상의 예시입니다. 인물·장소·수치는 모두 지어낸 것입니다.')),h('aside',{className:'ed-article-aside','aria-label':'관련 기사'},h('span',{className:'dew-overline'},'RELATED'),STORIES.slice(1,3).map(s=>h(StoryCard,{key:s.title,story:{...s,dek:null}})))),h('div',{'data-case':'story-cta','data-tag':'derived'},h(EditorialCTA,{tone:'light'})),h(Footer))}
function Parts(){const P=(n,tag,el)=>h('section',{className:'ed-part','data-case':'part-'+n,'data-tag':tag},h('header',null,h('span',null,n),h('span',null,tag)),el);return h('div',{className:'dew-container ed-parts',style:{paddingTop:32,paddingBottom:48}},
 P('EditorialHeader','observed',h(F,null,h(EditorialHeader),h('div',{style:{height:16}}),h(EditorialHeader,{compact:true,tagline:'Archive'}))),
 P('CategoryNav','derived',h(CategoryNav,{items:CATS,current:'Essay'})),
 P('FeatureStory','observed',h(FeatureStory,{story:COVER,reverse:true})),
 P('StoryCard','derived',h('div',{className:'ed-grid'},h('div',null,h(StoryCard,{story:STORIES[0]})),h('div',null,h(StoryCard,{story:STORIES[3]})),h('div',null,h(StoryCard,{story:STORIES[4]})),h('div',null,h(StoryCard,{loading:true})))),
 P('StoryCard · row','derived',h(StoryCard,{story:STORIES[1],layout:'row'})),
 P('MediaCard','derived',h('div',{className:'ed-grid'},h('div',null,h(MediaCard,{label:'4:3',caption:'캡션 + 크레딧',credit:'오하람'})),h('div',null,h(MediaCard,{label:'GALLERY',kind:'gallery',tone:'mid',caption:'갤러리'})),h('div',null,h(MediaCard,{label:'VIDEO',kind:'video',tone:'dark',caption:'영상 · 3분'})))),
 P('EditorialGrid','derived',h(EditorialGrid,null,STORIES.slice(0,3).map(s=>h(StoryCard,{key:s.title,story:s})))),
 P('QuoteBlock','derived',h(QuoteBlock,{quote:'오래 머무는 손님이 많을수록 책은 덜 팔려요. 그래도 괜찮습니다.',cite:'시집 서점 주인'})),
 P('ImageCaption','derived',h('div',{style:{display:'grid',gap:12}},h(ImageCaption,{caption:'망원동의 한 책방, 오후 5시 40분',credit:'오하람'}),h(ImageCaption,{caption:null,credit:'오하람'}))),
 P('ArticleMeta','derived',h('div',{style:{display:'grid',gap:12}},h(ArticleMeta,{category:'FEATURES',author:'한지우',photographer:'오하람',date:'2026.09.25',read:'12분'}),h(ArticleMeta,{author:null,read:'4분'}))),
 P('EditorialCTA','derived',h('div',{style:{display:'grid',gap:16}},h(EditorialCTA),h(EditorialCTA,{tone:'light',state:'error'}),h(EditorialCTA,{tone:'light',state:'success'}))),
 P('Footer','derived',h(Footer)))}
const PAGES=[['home','EditorialHome',EditorialHome],['list','ArticleList',ArticleList],['story','StoryDetail',StoryDetail],['parts','Parts · 11',Parts]];
function EditorialKit(){const q=new URLSearchParams(location.search).get('view');const [v,setV]=React.useState(PAGES.some(p=>p[0]===q)?q:'home');const Cur=PAGES.find(p=>p[0]===v)[2];return h('div',{className:'dp'},h('div',{className:'ed-kit-tabs'},h('div',{role:'tablist','aria-label':'편집 예시'},PAGES.map(([k,l])=>h('button',{key:k,role:'tab','aria-selected':v===k,onClick:()=>setV(k)},l)))),h('main',{style:{flex:1}},h(Cur,{key:v})))}
window.DEW_ED={EditorialHeader,CategoryNav,FeatureStory,StoryCard,MediaCard,EditorialGrid,QuoteBlock,ImageCaption,ArticleMeta,EditorialCTA,Footer,EditorialHome,ArticleList,StoryDetail,Parts,EditorialKit};
})();
