/* DEW · 3 UI kits (derived from archived IAK kit slots). Fictional data only. */
(function(){
const h=React.createElement,F=React.Fragment,D=window.DEW;const {Icon,Button,TextField,Select,Checkbox,Switch,Badge,Card,Table,Menu}=D;
const Ph=(l,r,t)=>h('div',{className:'dew-photo'+(t?' dew-photo--'+t:''),style:{aspectRatio:r}},h('span',null,'PHOTO · ',l));
const Top=(sub,links,active)=>{const [o,setO]=React.useState(false);return h(F,null,h('header',{className:'dp-top'},h('div',{className:'dp-top-in'},h('button',{type:'button',className:'dp-ib dp-menu-btn','aria-label':'메뉴','aria-expanded':o,onClick:()=>setO(!o)},h(Icon,{name:o?'eva:close-fill':'solar:list-bold'})),h('span',{className:'dew-wordmark'},'DEW',h('small',{className:'dp-hide-sm'},sub)),h('nav',{className:'dp-nav','aria-label':'메뉴'},links.map((l,i)=>h('a',{key:l,href:'#','aria-current':i===active?'page':undefined},l))),h('div',{className:'dp-tools'},h('button',{type:'button',className:'dp-ib','aria-label':'검색'},h(Icon,{name:'eva:search-fill'}))))),o&&h('nav',{className:'dp-drawer',style:{display:'flex'}},links.map(l=>h('a',{key:l,href:'#'},l))))};
/* front page */
const STORIES=[['ESSAY','종이의 촉감에 대하여','글 정민','4/3','light'],['INTERVIEW','작은 출판사의 다섯 번째 책','글 이도현','4/3','mid'],['REVIEW','가을 음반 다섯 장','글 박세린','4/3',null]];
function FrontPage(){return h('div',{className:'dp'},Top('WEBZINE',['Features','Essay','Interview','Review','Archive'],0),
 h('main',{className:'dp-body'},
  h('section',{'data-case':'masthead','data-tag':'observed',style:{borderBottom:'var(--dew-rule-heavy)',paddingBottom:16,display:'grid',gap:12}},h('div',{className:'row',style:{justifyContent:'space-between'}},h('span',{className:'dew-overline'},'No. 27 · Autumn 2026'),h('span',{className:'dew-overline dp-hide-sm'},'Editorial Webzine')),h('h1',{className:'dew-masthead',style:{fontSize:'clamp(64px,16vw,220px)',lineHeight:.85}},'DEW')),
  h('section',{className:'g12','data-case':'cover','data-tag':'observed',style:{alignItems:'end'}},h('div',{className:'s8'},Ph('COVER 16:10','16/10','dark')),h('div',{className:'s4 stack'},h('span',{className:'dew-overline dew-overline--red'},'COVER STORY'),h('h2',{className:'dew-h1'},'골목 끝, 불 켜진 서점'),h('p',{className:'dew-lead'},'오래된 동네의 서점들은 어떻게 저녁을 맞이하는가. 세 곳의 책방 주인과 보낸 가을 오후.'),h('div',{className:'dew-byline'},h('span',null,'글 한지우'),h('span',null,'사진 오하람'),h('span',null,'12분')),h('div',null,h(Button,{variant:'text'},'READ STORY')))),
  h('section',{className:'g12','data-case':'grid','data-tag':'derived',style:{borderTop:'var(--dew-rule)',paddingTop:24}},STORIES.map(([o,t,b,r,tn],i)=>h('a',{key:t,href:'#',className:'story s4',style:i===1?{marginTop:48}:undefined},Ph(r,r,tn),h('span',{className:'dew-overline'},o),h('h3',null,t),h('span',{className:'dew-caption'},b)))),
  h('section',{className:'g12','data-case':'list','data-tag':'derived'},h('div',{className:'s5'},h('h2',{className:'dew-h2',style:{borderTop:'var(--dew-rule-heavy)',paddingTop:12}},'Most read')),h('ol',{className:'s7 list-rule',style:{listStyle:'none',margin:0,padding:0}},['밤의 도서관','편집자의 책상','오래된 극장의 마지막 상영','지하철 2호선의 시'].map((t,i)=>h('li',{key:t,className:'row',style:{gap:24,alignItems:'baseline'}},h('span',{style:{font:'400 44px/1 var(--dew-font-display)',color:'var(--dew-grey-300)',width:48}},String(i+1).padStart(2,'0')),h('a',{href:'#',className:'grow',style:{font:'var(--dew-text-h3)',textDecoration:'none'}},t))))),
  h('section',{className:'g12','data-case':'newsletter','data-tag':'derived',style:{background:'var(--dew-black)',color:'#fff',padding:'40px var(--dew-container-pad)',marginInline:'calc(var(--dew-container-pad) * -1)'}},h('div',{className:'s6 stack'},h('span',{className:'dew-overline',style:{color:'#fff'}},'NEWSLETTER'),h('h2',{className:'dew-h2'},'매주 목요일, 한 편의 긴 글')),h('form',{className:'s6 row',style:{alignItems:'flex-end'},onSubmit:e=>e.preventDefault()},h('div',{className:'grow dew-field'},h('label',{htmlFor:'nl',style:{color:'#fff'}},'이메일'),h('input',{id:'nl',className:'dew-input',type:'email',placeholder:'reader@example.com'})),h(Button,{type:'submit'},'구독하기')))),
 h('footer',{className:'dp-foot'},h('span',null,'DEW · 가상 데이터 · 파생 UI kit'),h('span',null,'© 2026')))}
/* reader CRM */
const COLS=[['신규','neutral',[['김서연','뉴스레터 가입','2일 전'],['Lee J.','특집 공유 유입',null]]],['체험','warning',[['박도윤','MEMBER 체험 5/14일','오늘'],['최유나','아카이브 12편 읽음','어제']]],['구독','success',[['오하람','PATRON · 연간','3개월'],['정민','MEMBER','8개월'],['한지우','MEMBER · 종이판','1년']]],['이탈 위험','error',[['윤재','30일 미방문','—']]]];
function ReaderCRM(){return h('div',{className:'dp'},Top('READERS',['Pipeline','Readers','Campaigns','Reports'],0),h('main',{className:'dp-body'},
 h('div',{className:'dp-head'},h('div',null,h('div',{className:'dew-overline dew-overline--red'},'READER PIPELINE'),h('h1',null,'독자 관계')),h('div',{className:'dp-actions'},h(Button,{variant:'secondary'},'내보내기'),h(Button,null,'캠페인 만들기'))),
 h('div',{className:'g12','data-case':'kpi','data-tag':'derived'},[['신규','214'],['체험 전환','18%'],['유료 구독','3,902'],['이탈 위험','41']].map(([k,v])=>h('div',{key:k,className:'s3'},h('div',{className:'kpi'},h('span',{className:'dew-overline'},k),h('span',{className:'dew-numeral'},v))))),
 h('div',{className:'g12','data-case':'pipeline','data-tag':'derived'},COLS.map(([t,tone,cards])=>h('section',{key:t,className:'s3 stack','aria-label':t},h('div',{className:'row',style:{justifyContent:'space-between',borderTop:'var(--dew-rule-heavy)',paddingTop:10}},h('h2',{className:'dew-h3'},t),h(Badge,{tone},cards.length)),cards.map(([n,d,w])=>h('article',{key:n,className:'dew-card',style:{gap:8,padding:16}},h('b',null,n),h('span',{className:'dew-small dew-muted'},d),h('span',{className:'dew-caption'},w||h('span',{className:'dew-miss'},'활동 없음'))))))),
 h('section',{className:'g12','data-case':'assistant','data-tag':'derived'},h('div',{className:'s8'},h(Table,{caption:'최근 활동',columns:[{id:'n',header:'독자',cell:r=>r.n},{id:'a',header:'활동',cell:r=>r.a},{id:'p',header:'플랜',cell:r=>h(Badge,{tone:r.p==='PATRON'?'info':'neutral'},r.p)},{id:'w',header:'시각',cell:r=>r.w}],rows:[{id:1,n:'오하람',a:'특집 댓글',p:'PATRON',w:'10:24'},{id:2,n:'정민',a:'아카이브 5편 읽음',p:'MEMBER',w:'09:02'},{id:3,n:'김서연',a:'뉴스레터 열람',p:'READER',w:'어제'}],rowKey:r=>r.id,minWidth:480})),
  h('aside',{className:'s4 stack','aria-label':'어시스턴트 제안'},h('span',{className:'dew-overline dew-overline--red'},'ASSISTANT'),h('p',{className:'dew-lead'},'체험 5일 차 독자 2명에게 “가을호 커버 스토리” 추천 메일을 보내면 전환에 도움이 될 수 있습니다.'),h('div',{className:'row'},h(Button,{size:'sm'},'메일 초안'),h(Button,{variant:'text',size:'sm'},'무시'))))))}
/* editorial audit */
const AR=[{id:1,t:'골목 끝, 불 켜진 서점',ph:true,cap:true,sp:true,ln:true},{id:2,t:'도시의 여백을 걷다',ph:true,cap:false,sp:true,ln:true},{id:3,t:'작은 출판사 인터뷰',ph:false,cap:false,sp:true,ln:null},{id:4,t:'가을 음반 리뷰',ph:true,cap:true,sp:false,ln:true},{id:5,t:'2026 가을호 특집 — 도시의 오래된 골목과 새로 문을 연 작은 서점들을 따라 걷는 긴 산책 기록',ph:null,cap:null,sp:null,ln:null}];
const mk=v=>v==null?h('span',{className:'dew-miss'},'미검사'):v?h(Badge,{tone:'success'},'OK'):h(Badge,{tone:'error'},'수정');
function EditorialAudit(){const done=AR.filter(r=>r.ph&&r.cap&&r.sp&&r.ln).length;return h('div',{className:'dp'},Top('AUDIT',['Issue 27','Checklist','Rights','History'],1),h('main',{className:'dp-body'},
 h('div',{className:'dp-head'},h('div',null,h('div',{className:'dew-overline dew-overline--red'},'PRE-PRESS CHECK · No. 27'),h('h1',null,'발행 전 점검'),h('p',null,'사진 권리·캡션·맞춤법·링크를 기사별로 확인합니다. 모두 가상 데이터.')),h('div',{className:'dp-actions'},h(Button,{disabled:done<AR.length},'발행 승인'))),
 h('div',{className:'g12','data-case':'summary','data-tag':'derived'},[['점검 완료',done+' / '+AR.length],['사진 권리 미확인',AR.filter(r=>!r.ph).length],['캡션 수정',AR.filter(r=>r.cap===false).length],['미검사 항목',AR.reduce((a,r)=>a+['ph','cap','sp','ln'].filter(k=>r[k]==null).length,0)]].map(([k,v])=>h('div',{key:k,className:'s3'},h('div',{className:'kpi'},h('span',{className:'dew-overline'},k),h('span',{className:'dew-numeral'},v))))),
 h('div',{className:'row','data-case':'filters','data-tag':'code',style:{gap:24}},h(Checkbox,{label:'수정 필요만',defaultChecked:false}),h(Switch,{label:'미검사 포함',defaultChecked:true}),h('div',{style:{minWidth:200}},h(Select,{label:'담당','aria-label':'담당'},h('option',null,'전체'),h('option',null,'이도현')))),
 h('div',{'data-case':'table','data-tag':'code'},h(Table,{caption:'기사별 점검',columns:[{id:'t',header:'기사',cell:r=>r.t,sortValue:r=>r.t},{id:'ph',header:'사진 권리',cell:r=>mk(r.ph)},{id:'cap',header:'캡션',cell:r=>mk(r.cap)},{id:'sp',header:'맞춤법',cell:r=>mk(r.sp)},{id:'ln',header:'링크',cell:r=>mk(r.ln)}],rows:AR,rowKey:r=>r.id,minWidth:640})),
 h('div',{className:'banner','data-case':'blocker','data-tag':'derived',role:'status'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-triangle-fill'})),h('div',{className:'stack',style:{gap:6}},h('b',null,'발행 승인 전 해결할 항목이 있습니다'),h('span',{className:'dew-small dew-muted'},'“작은 출판사 인터뷰” 사진 권리 확인서가 없습니다.')))))}
window.DEW_KITS={FrontPage,ReaderCRM,EditorialAudit};
})();
