/* DEW · 10 derived patterns rendered with DEW components. Fictional newsroom data only. */
(function(){
const h=React.createElement,F=React.Fragment,D=window.DEW;
const {Icon,Button,TextField,Textarea,Select,Checkbox,Switch,Badge,Card,Skeleton,Dialog,Menu,Table,Pagination,AlertDialog}=D;const TV=D.preview.ToastView;
const LONG='2026 가을호 특집 — 도시의 오래된 골목과 새로 문을 연 작은 서점들을 따라 걷는 아주 긴 산책 기록과 그 주변 사람들의 이야기';
const months=['4월','5월','6월','7월','8월','9월'];const reads=[182,204,196,231,248,263],prev=[160,171,180,190,205,214];
const SEC=['특집','인터뷰','에세이','리뷰'];const ST=['발행됨','검토 중','초안','반려'],TONE={'발행됨':'success','검토 중':'warning','초안':'neutral','반려':'error'};
const TITLES=['골목 끝, 불 켜진 서점','도시의 여백을 걷다','작은 출판사 인터뷰','가을 음반 리뷰','종이의 촉감에 대하여','밤의 도서관','편집자의 책상','오래된 극장의 마지막 상영','사진가 K의 한 해','지하철 2호선의 시','바다를 닮은 식탁','연말 특집 예고'];
const AUTH=['한지우','이도현',null,'박세린','정민','오하람'];
const arts=TITLES.map((t,i)=>({id:'DEW-'+(2701+i),t,a:AUTH[i%6],sec:SEC[i%4],s:ST[i%4],d:'2026-09-'+String(25-i).padStart(2,'0'),v:i%5===2?null:24800-i*1730}));
const miss=(v,t)=>v==null||v===''?h('span',{className:'dew-miss'},t||'—'):v;
const num=v=>v==null?miss(null):v.toLocaleString('ko-KR');
const Photo=(label,ratio,tone)=>h('div',{className:'dew-photo'+(tone?' dew-photo--'+tone:''),style:{aspectRatio:ratio}},h('span',null,'PHOTO · ',label));
/* charts: data roles black/grey, red = single highlight */
function Line({a11y}){const W=600,H=200,max=300,step=W/5,pts=s=>s.map((v,i)=>`${i*step},${H-v/max*H}`).join(' ');return h('svg',{className:'chart',viewBox:`0 -8 ${W} ${H+32}`,role:'img','aria-label':a11y,preserveAspectRatio:'none'},
 [0,.5,1].map(g=>h('line',{key:g,x1:0,x2:W,y1:H-H*g,y2:H-H*g,stroke:'var(--dew-line)'})),
 h('polyline',{points:pts(prev),fill:'none',stroke:'var(--dew-data-3)',strokeWidth:1.5,strokeDasharray:'4 4',vectorEffect:'non-scaling-stroke'}),
 h('polyline',{points:pts(reads),fill:'none',stroke:'var(--dew-data-1)',strokeWidth:2,vectorEffect:'non-scaling-stroke'}),
 h('circle',{cx:W,cy:H-reads[5]/max*H,r:5,fill:'var(--dew-data-accent)'}),
 months.map((l,i)=>h('text',{key:l,x:Math.min(W-14,Math.max(14,i*step)),y:H+22,textAnchor:'middle',fill:'var(--dew-fg-3)',fontSize:12},l)))}
function Bars({a11y}){const v=[42,28,19,11];return h('div',{className:'stack',role:'img','aria-label':a11y,style:{gap:14}},SEC.map((s,i)=>h('div',{key:s,className:'stack',style:{gap:6}},h('div',{className:'row',style:{justifyContent:'space-between'}},h('span',{className:'dew-small'},s),h('span',{className:'dew-caption'},v[i]+'%')),h('div',{style:{height:6,background:'var(--dew-grey-100)'}},h('div',{style:{height:6,width:v[i]+'%',background:i?'var(--dew-data-1)':'var(--dew-data-accent)'}})))))}
const Legend=()=>h('div',{className:'legend'},h('span',null,h('i',{style:{background:'var(--dew-data-1)'}}),'이번 분기'),h('span',null,h('i',{style:{background:'var(--dew-data-3)'}}),'지난 분기'),h('span',null,h('i',{style:{background:'var(--dew-data-accent)',height:6,width:6,borderRadius:'50%'}}),'최신'));
/* shell */
const NAV=[['dashboard','편집국'],['analytics','독자 분석'],['table','기사'],['chat','어시스턴트'],['builder','지면 빌더'],['billing','구독'],['settings','설정']];
function Shell({active,children,state}){const [nav,setNav]=React.useState(false);const links=NAV.map(([k,l])=>h('a',{key:k,href:`screen.html?p=${k}`,'aria-current':active===k?'page':undefined},l));
 return h('div',{className:'dp','data-nav':nav?'open':undefined},
  h('header',{className:'dp-top'},h('div',{className:'dp-top-in'},h('button',{type:'button',className:'dp-ib dp-menu-btn','aria-label':nav?'메뉴 닫기':'메뉴 열기','aria-expanded':nav,onClick:()=>setNav(!nav)},h(Icon,{name:nav?'eva:close-fill':'solar:list-bold'})),
   h('a',{className:'dew-wordmark',href:'screen.html?p=dashboard'},'DEW',h('small',{className:'dp-hide-sm'},'NEWSROOM')),h('nav',{className:'dp-nav','aria-label':'주 메뉴'},links),
   h('div',{className:'dp-tools'},h('button',{type:'button',className:'dp-ib','aria-label':'검색'},h(Icon,{name:'eva:search-fill'})),h('button',{type:'button',className:'dp-ib','aria-label':'알림 3개'},h(Icon,{name:'solar:bell-bold'}),h('span',{className:'dp-dot'})),h('span',{className:'dp-avatar',role:'img','aria-label':'내 계정'},'HJ')))),
  h('nav',{className:'dp-drawer','aria-label':'주 메뉴 (모바일)'},links),
  h('main',{className:'dp-body','data-state':state},children),
  h('footer',{className:'dp-foot'},h('span',null,'DEW_V1 · 파생 사례 · 가상 데이터'),h('span',null,'No. 27 · 2026 가을')));}
const Head=(ov,t,d,actions)=>h('div',{className:'dp-head'},h('div',null,h('div',{className:'dew-overline dew-overline--red'},ov),h('h1',null,t),d&&h('p',null,d)),actions&&h('div',{className:'dp-actions'},actions));
const Err=(msg)=>h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',{className:'stack',style:{gap:8,flex:1}},h('b',null,'데이터를 불러오지 못했습니다'),h('span',{className:'dew-muted dew-small'},msg),h('div',null,h(Button,{variant:'secondary',size:'sm'},h(Icon,{name:'eva:refresh-fill',size:16}),'다시 시도'))));
const Empty=(n,t,d,action)=>h('div',{className:'empty'},h('div',{className:'n','aria-hidden':'true'},n),h('h2',null,t),h('p',null,d),action&&h('div',{className:'row'},action));
const Kpi=(t,v,d,up,cls='s3')=>h('div',{className:cls},h('div',{className:'kpi'},h('div',{className:'dew-overline'},t),h('div',{className:'dew-numeral'},v),d&&h('div',{className:'delta '+(up?'up':'down')},h(Icon,{name:up?'eva:arrow-upward-fill':'eva:arrow-downward-fill',size:14}),d)));
const SkKpi=cls=>h('div',{className:cls},h('div',{className:'kpi','aria-busy':'true'},h(Skeleton,{height:12,width:'50%'}),h(Skeleton,{height:48,width:'70%'})));
const aCols=(compact)=>[{id:'t',header:'제목',cell:r=>h('a',{href:'screen.html?p=detail'},r.t),sortValue:r=>r.t},{id:'a',header:'필자',cell:r=>miss(r.a,'미지정')},...(compact?[]:[{id:'sec',header:'섹션',cell:r=>r.sec}]),{id:'s',header:'상태',cell:r=>h(Badge,{tone:TONE[r.s]},r.s),sortValue:r=>r.s},{id:'d',header:'날짜',cell:r=>r.d,sortValue:r=>r.d},{id:'v',header:'조회',align:'right',cell:r=>num(r.v),sortValue:r=>r.v},
 {id:'act',header:'',align:'right',cell:r=>h(Menu,{label:r.t+' 작업',trigger:h(Button,{variant:'text',size:'sm','aria-label':r.t+' 작업'},h(Icon,{name:'eva:more-horizontal-fill',size:20})),items:[{id:'o',label:'열기',onSelect(){}},{id:'c',label:'복제',onSelect(){}},{id:'x',label:'보관',danger:true,separatorBefore:true,onSelect(){}}]})}];
/* 01 dashboard */
function Dashboard({s}){const L=s==='loading';return h(Shell,{active:'dashboard',state:s},
 Head('EDITORIAL DESK · 9월 25일','편집국',s==='empty'?null:'이번 호 진행 상황과 오늘 읽힌 기사를 한 지면에서 봅니다.',h(F,null,h(Button,{variant:'secondary'},'이번 호 보기'),h(Button,null,h(Icon,{name:'eva:plus-fill',size:16}),'새 기사'))),
 s==='error'?Err('편집국 지표 서버에 연결할 수 없습니다. 잠시 후 다시 시도하세요.'):null,
 s==='empty'?Empty('00','아직 이번 호 기사가 없습니다','첫 기사를 작성하면 발행 현황과 독자 지표가 이 지면에 채워집니다.',h(Button,null,'첫 기사 쓰기')):
 h(F,null,
  h('div',{className:'g12'},L?[1,2,3,4].map(i=>SkKpi('s3',i)):s==='error'?[['발행',null],['조회',null],['구독자',null],['평균 체류',null]].map(([t])=>h('div',{key:t,className:'s3'},h('div',{className:'kpi'},h('div',{className:'dew-overline'},t),h('div',{className:'dew-numeral dew-miss'},'—')))):[Kpi('이번 주 발행','14','+3 지난주',true),Kpi('오늘 조회','26,310','+8.2%',true),Kpi('구독자','12,480','+124',true),Kpi('평균 체류','3분 42초','-12초',false)].map((k,i)=>h(F,{key:i},k))),
  h('div',{className:'g12'},
   h('article',{className:'s7 stack',style:{gap:16}},L?h(Skeleton,{height:420}):Photo('LEAD STORY 16:10','16/10','dark'),h('div',{className:'dew-overline dew-overline--red'},'이번 호 커버'),L?h(Skeleton,{height:40,width:'80%'}):h('h2',{className:'dew-h2'},'골목 끝, 불 켜진 서점'),h('div',{className:'dew-byline'},h('span',null,'글 한지우'),h('span',null,'사진 오하람'),h('span',null,'발행 예정 10월 1일'))),
   h('div',{className:'s5 stack',style:{gap:24}},
    h('div',{className:'stack'},h('div',{className:'row',style:{justifyContent:'space-between'}},h('h2',{className:'dew-h3'},'월간 조회'),h(Legend)),L?h(Skeleton,{height:200}):s==='error'?h('p',{className:'dew-muted dew-small'},'차트를 표시할 수 없습니다.'):h(Line,{a11y:'4월부터 9월까지 월간 조회 추이, 9월 263천'})),
    h('div',{className:'stack'},h('h2',{className:'dew-h3'},'오늘 많이 읽힌 기사'),h('ol',{className:'list-rule',style:{listStyle:'none',margin:0,padding:0}},(L?[0,1,2,3]:arts.slice(0,4)).map((a,i)=>h('li',{key:i,className:'row',style:{alignItems:'baseline',gap:16}},h('span',{style:{font:'400 28px/1 var(--dew-font-display)',color:'var(--dew-fg-3)',width:28}},i+1),L?h(Skeleton,{height:18,width:'70%'}):h(F,null,h('a',{href:'screen.html?p=detail',className:'grow',style:{textDecoration:'none'}},a.t),h('span',{className:'dew-caption'},num(a.v)))))))))))}
/* 02 analytics */
function Analytics({s}){const L=s==='loading';return h(Shell,{active:'analytics',state:s},Head('READERS · 3분기','독자 분석','섹션별 읽힘과 구독 전환을 분기 단위로 비교합니다.',h(F,null,h(Select,{label:'기간','aria-label':'기간',defaultValue:'q3'},h('option',{value:'q3'},'2026 3분기'),h('option',{value:'q2'},'2026 2분기')),h(Button,{variant:'secondary'},h(Icon,{name:'eva:download-fill',size:16}),'CSV'))),
 s==='error'&&Err('분석 데이터 집계가 지연되고 있습니다.'),
 s==='empty'?Empty('0','이 기간에 집계된 독자가 없습니다','기간을 넓히거나 발행된 기사가 있는 분기를 선택하세요.',h(Button,{variant:'secondary'},'기간 초기화')):
 h(F,null,h('div',{className:'g12'},L?[1,2,3,4].map(i=>SkKpi('s3')):[Kpi('순 독자','48,210','+6.1%',true),Kpi('구독 전환','3.4%','+0.3%p',true),Kpi('재방문','41%','-2%p',false),Kpi('공유','2,904',null,true)].map((k,i)=>h(F,{key:i},k))),
  h('div',{className:'g12'},h('section',{className:'s8 stack'},h('div',{className:'row',style:{justifyContent:'space-between',borderTop:'var(--dew-rule)',paddingTop:12}},h('h2',{className:'dew-h3'},'조회 추이'),h(Legend)),L?h(Skeleton,{height:240}):s==='error'?h('p',{className:'dew-muted'},'—'):h(Line,{a11y:'월간 조회 추이'})),
   h('section',{className:'s4 stack'},h('h2',{className:'dew-h3',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'섹션 비중'),L?h(Skeleton,{height:200}):h(Bars,{a11y:'섹션별 조회 비중, 특집 42%'}))),
  h(Table,{caption:'많이 읽힌 기사 · 3분기',columns:aCols(true).slice(0,-1),rows:s==='error'?[]:arts.slice(0,6),rowKey:r=>r.id,loading:L,error:s==='error'?'표를 불러오지 못했습니다.':undefined,defaultSort:{columnId:'v',direction:'descending'}})))}
/* 03 table */
function TablePage({s}){const rows=s==='empty'?[]:s==='long-text'?arts.map((a,i)=>i%3===0?{...a,t:LONG,a:a.a||null}:a):arts;const [w,setW]=React.useState(innerWidth);React.useEffect(()=>{const r=()=>setW(innerWidth);addEventListener('resize',r);return()=>removeEventListener('resize',r)},[]);
 return h(Shell,{active:'table',state:s},Head('ARCHIVE','기사',`전체 ${s==='empty'?0:arts.length}건 · 필자와 상태로 걸러 보세요.`,h(Button,null,h(Icon,{name:'eva:plus-fill',size:16}),'새 기사')),
 h('div',{className:'g12'},h('div',{className:'s6'},h(TextField,{label:'검색',type:'search',placeholder:'제목, 필자, 태그',defaultValue:s==='empty'?'존재하지 않는 제목':''})),h('div',{className:'s3'},h(Select,{label:'상태'},h('option',null,'전체'),ST.map(x=>h('option',{key:x},x)))),h('div',{className:'s3'},h(Select,{label:'섹션'},h('option',null,'전체'),SEC.map(x=>h('option',{key:x},x))))),
 h(Table,{caption:'9월 기사',columns:aCols(w<834),rows:s==='error'||s==='loading'?[]:rows,rowKey:r=>r.id,loading:s==='loading',error:s==='error'?'기사 목록을 불러오지 못했습니다. 네트워크를 확인하세요.':undefined,emptyMessage:'검색 조건에 맞는 기사가 없습니다.',pagination:{pageSize:6},minWidth:w<834?0:720}))}
/* 04 detail */
function Detail({s}){const L=s==='loading',M=s==='missing-data';return h(Shell,{active:'table',state:s},
 h('nav',{className:'dew-byline','aria-label':'이동 경로'},h('a',{href:'screen.html?p=table'},'기사'),h('span',null,'DEW-2701')),
 s==='error'?h(F,null,Err('기사 DEW-2701을 찾을 수 없거나 권한이 없습니다.')):
 h(F,null,h('header',{className:'g12',style:{alignItems:'end',borderBottom:'var(--dew-rule-heavy)',paddingBottom:24}},h('div',{className:'s8 stack'},h('div',{className:'row'},h('span',{className:'dew-overline dew-overline--red'},'ESSAY'),h(Badge,{tone:'warning'},'검토 중')),L?h(Skeleton,{height:72}):h('h1',{className:'dew-display',style:{overflowWrap:'anywhere'}},'골목 끝, 불 켜진 서점'),L?h(Skeleton,{height:20,width:'60%'}):h('p',{className:'dew-lead'},M?h('span',{className:'dew-miss'},'리드 문단이 아직 없습니다'):'오래된 동네의 서점들은 어떻게 저녁을 맞이하는가. 세 곳의 책방 주인과 보낸 가을 오후.')),
  h('div',{className:'s4 stack',style:{gap:12}},h('div',{className:'dp-actions'},h(Button,{variant:'secondary'},'미리보기'),h(Button,null,'발행 요청')))),
 h('div',{className:'g12'},h('div',{className:'s8 stack',style:{gap:24}},L?h(Skeleton,{height:420}):M?h('div',{className:'dew-photo dew-photo--light',style:{aspectRatio:'3/2',alignItems:'center',justifyContent:'center'}},h('span',null,'대표 사진 없음 · 업로드 필요')):Photo('HERO 3:2','3/2','mid'),
   h('div',{className:'stack',style:{gap:16,maxWidth:'66ch'}},(L?[1,2,3]:['해가 짧아지면 골목의 서점들은 조금 일찍 불을 켠다. 첫 번째로 찾은 곳은 문을 연 지 삼 년이 된 작은 책방이다.','주인은 매일 저녁 여섯 시에 추천 책 한 권을 창가에 올려 둔다. 그날 들어온 손님의 대화에서 고른 책이다.','세 번째 서점에서는 오래된 극장 포스터가 벽 한 면을 채우고 있었다.']).map((p,i)=>L?h(Skeleton,{key:i,height:18}):h('p',{key:i},p)))),
  h('aside',{className:'s4 stack','aria-label':'기사 정보'},h('dl',{className:'list-rule',style:{margin:0}},[['필자',M?null:'한지우'],['사진',M?null:'오하람'],['섹션','에세이'],['분량',M?null:'4,210자'],['발행 예정','2026-10-01'],['태그',M?null:'서점 · 골목 · 가을']].map(([k,v])=>h('div',{key:k,className:'row',style:{justifyContent:'space-between'}},h('dt',{className:'dew-overline'},k),h('dd',{style:{margin:0}},L?h(Skeleton,{width:80,height:14}):miss(v,'미입력'))))),
   h(Card,{title:'편집자 메모',footer:'2시간 전 · 이도현'},M?h('span',{className:'dew-miss'},'메모 없음'):h('p',{className:'dew-small'},'두 번째 문단 사진 캡션 확인 필요. 서점 이름 표기 통일.'))))))}
/* 05 settings */
function Settings({s}){return h(Shell,{active:'settings',state:s},Head('SETTINGS','매체 설정','웹진 이름, 발행 주기, 알림을 관리합니다.'),
 s==='success'&&h('div',{className:'banner ok',role:'status'},h('span',{className:'ic'},h(Icon,{name:'eva:checkmark-circle-2-fill'})),h('div',null,h('b',null,'설정을 저장했습니다'),h('div',{className:'dew-small dew-muted'},'다음 호부터 적용됩니다.'))),
 s==='error'&&h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',null,h('b',null,'저장하지 못했습니다'),h('div',{className:'dew-small dew-muted'},'표시된 항목을 확인하세요.'))),
 h('div',{className:'g12'},h('div',{className:'s4'},h('h2',{className:'dew-h3',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'기본 정보'),h('p',{className:'dew-small dew-muted',style:{marginTop:8}},'독자에게 보이는 이름과 소개입니다.')),
  h('div',{className:'s8 stack',style:{gap:20}},h(TextField,{label:'웹진 이름',defaultValue:'DEW',required:true,disabled:s==='saving'}),h(TextField,{label:'대표 이메일',defaultValue:s==='error'?'desk@':'desk@dew.example',error:s==='error'?'올바른 이메일 형식이 아닙니다.':undefined,disabled:s==='saving'}),h(Textarea,{label:'소개',defaultValue:'도시의 작은 장면을 기록하는 에디토리얼 웹진.',description:'검색 결과와 공유 카드에 표시됩니다.',disabled:s==='saving'}),h(Select,{label:'발행 주기',defaultValue:'m',disabled:s==='saving'},h('option',{value:'w'},'주간'),h('option',{value:'m'},'월간'),h('option',{value:'q'},'계간')))),
 h('div',{className:'g12'},h('div',{className:'s4'},h('h2',{className:'dew-h3',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'알림')),h('div',{className:'s8 stack'},h(Switch,{label:'새 댓글 알림',defaultChecked:true,disabled:s==='saving'}),h(Switch,{label:'발행 전날 편집자에게 리마인더 보내기',disabled:s==='saving'}),h(Checkbox,{label:'주간 리포트를 이메일로 받기',defaultChecked:true,disabled:s==='saving'}))),
 h('div',{className:'row',style:{justifyContent:'flex-end',borderTop:'var(--dew-rule)',paddingTop:16}},h(Button,{variant:'secondary',disabled:s==='saving'},'취소'),h(Button,{loading:s==='saving'},'저장')))}
/* 06 billing */
const PLANS=[['READER','무료',['주 1회 뉴스레터','공개 기사']],['MEMBER','₩6,900 / 월',['전체 아카이브','광고 없음','종이판 할인 10%']],['PATRON','₩19,000 / 월',['MEMBER 전부','연 2회 종이판','편집 모임 초대']]];
const inv=[{id:'INV-0931',d:'2026-09-01',p:'MEMBER',a:6900,s:'결제 완료'},{id:'INV-0831',d:'2026-08-01',p:'MEMBER',a:6900,s:'결제 완료'},{id:'INV-0731',d:'2026-07-01',p:'MEMBER',a:null,s:'환불'}];
function Billing({s}){const L=s==='loading';return h(Shell,{active:'billing',state:s},Head('SUBSCRIPTION','구독','현재 플랜과 결제 내역입니다.'),
 s==='error'&&Err('결제 정보를 가져오지 못했습니다. 카드 정보는 변경되지 않았습니다.'),
 h('div',{className:'g12'},PLANS.map(([n,p,f],i)=>h('div',{key:n,className:'s4'},L?h(Skeleton,{height:260}):h('section',{className:'dew-card',style:i===1&&s!=='empty'?{borderTop:'3px solid var(--dew-action)'}:undefined,'aria-label':n+' 플랜'},h('div',{className:'row',style:{justifyContent:'space-between'}},h('span',{className:'dew-overline'},n),i===1&&s!=='empty'&&h(Badge,{tone:'info'},'현재 플랜')),h('div',{style:{font:'var(--dew-text-h2)'}},p),h('ul',{className:'list-rule',style:{listStyle:'none',margin:0,padding:0}},f.map(x=>h('li',{key:x,className:'dew-small'},x))),h(Button,{variant:i===1&&s!=='empty'?'secondary':i===2?'primary':'secondary',disabled:s==='error'},i===1&&s!=='empty'?'플랜 관리':'선택'))))),
 h(Table,{caption:'결제 내역',columns:[{id:'id',header:'청구서',cell:r=>r.id},{id:'d',header:'날짜',cell:r=>r.d,sortValue:r=>r.d},{id:'p',header:'플랜',cell:r=>r.p},{id:'a',header:'금액',align:'right',cell:r=>r.a==null?miss(null):'₩'+r.a.toLocaleString('ko-KR')},{id:'s',header:'상태',cell:r=>h(Badge,{tone:r.s==='환불'?'neutral':'success'},r.s)}],rows:s==='empty'||s==='error'?[]:inv,rowKey:r=>r.id,loading:L,error:s==='error'?'결제 내역을 불러오지 못했습니다.':undefined,emptyMessage:'아직 결제 내역이 없습니다. 무료 READER 플랜 이용 중입니다.',minWidth:520}))}
/* 07 chat */
const MSG=[['u','이번 호 특집 제목 후보를 세 개 제안해 줘. 골목 서점이 주제야.'],['a','세 가지 방향으로 제안합니다.\n1. 골목 끝, 불 켜진 서점\n2. 저녁 여섯 시의 책방\n3. 작은 서점이 도시를 읽는 법'],['u','2번으로 리드 문단 초안도 부탁해.']];
function Chat({s}){const msgs=s==='empty'?[]:MSG;return h(Shell,{active:'chat',state:s},Head('EDITORIAL ASSISTANT','어시스턴트','제목·리드·교정 초안을 요청하세요. 결과는 편집자가 검토합니다.'),
 h('div',{className:'g12'},h('section',{className:'s8 stack',style:{gap:0,borderTop:'var(--dew-rule)'},'aria-label':'대화'},
  s==='empty'?Empty('?','무엇을 도와드릴까요?','예: “이번 호 특집 제목 후보 3개”, “리드 문단 교정”',h(F,null,['제목 후보','리드 초안','맞춤법 교정'].map(x=>h(Button,{key:x,variant:'secondary',size:'sm'},x)))):
  h('ol',{style:{listStyle:'none',margin:0,padding:0}},msgs.map(([r,t],i)=>h('li',{key:i,style:{padding:'20px 0',borderBottom:'var(--dew-rule-hair)',display:'grid',gridTemplateColumns:'88px minmax(0,1fr)',gap:16}},h('span',{className:'dew-overline',style:{color:r==='a'?'var(--dew-action)':undefined}},r==='a'?'ASSISTANT':'편집자'),h('p',{style:{whiteSpace:'pre-line',font:r==='a'?'var(--dew-text-lead)':'var(--dew-text-body)',color:'var(--dew-fg)'}},t))),
   s==='streaming'&&h('li',{style:{padding:'20px 0',display:'grid',gridTemplateColumns:'88px minmax(0,1fr)',gap:16},'aria-live':'polite'},h('span',{className:'dew-overline',style:{color:'var(--dew-action)'}},'ASSISTANT'),h('div',{className:'stack',style:{gap:8}},h('p',{style:{font:'var(--dew-text-lead)'}},'해가 짧아지면 골목의 서점들은 조금 일찍 불을 켠다▍'),h('span',{className:'dew-caption'},'작성 중…'))),
   s==='error'&&h('li',{style:{padding:'20px 0'}},h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',{className:'stack',style:{gap:8}},h('b',null,'응답을 생성하지 못했습니다'),h('div',null,h(Button,{variant:'secondary',size:'sm'},'다시 생성'))))))),
  h('form',{className:'stack',style:{paddingTop:16},onSubmit:e=>e.preventDefault()},h(Textarea,{label:'메시지',rows:3,placeholder:'요청을 입력하세요',disabled:s==='streaming'}),h('div',{className:'row',style:{justifyContent:'flex-end'}},s==='streaming'?h(Button,{variant:'secondary'},'중지'):h(Button,{type:'submit'},'보내기')))),
 h('aside',{className:'s4 stack','aria-label':'참고 자료'},h('h2',{className:'dew-h3',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'참고 자료'),h('ul',{className:'list-rule',style:{listStyle:'none',margin:0,padding:0}},['DEW 표기 원칙 v3','가을호 기획안','서점 인터뷰 녹취'].map(x=>h('li',{key:x,className:'row'},h(Icon,{name:'eva:file-text-fill',size:16}),h('span',{className:'dew-small'},x)))),h(Checkbox,{label:'참고 자료를 답변에 인용',defaultChecked:true})))}
/* 08 builder */
const BLOCKS=[['hero','커버 사진','s8',260],['title','특집 제목','s4',260],['text','리드 문단','s4',140],['quote','인용','s4',140],['grid','사진 3단','s4',140]];
function Builder({s}){const sel=s==='selected'||s==='dragging'?'title':null;const blocks=s==='empty'?[]:BLOCKS;return h(Shell,{active:'builder',state:s},Head('LAYOUT BUILDER','지면 빌더','블록을 12단 격자에 배치해 특집 지면을 구성합니다.',h(F,null,h(Button,{variant:'secondary'},'미리보기'),h(Button,{disabled:s==='empty'},'지면 저장'))),
 h('div',{className:'g12'},h('aside',{className:'s3 stack','aria-label':'블록'},h('div',{className:'dew-overline',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'BLOCKS'),['커버 사진','제목','본문','인용','사진 그리드','구분선'].map(b=>h('button',{key:b,type:'button',className:'dew-button dew-button--secondary dew-button--md',style:{justifyContent:'flex-start'}},h('span',null,h(Icon,{name:'solar:widget-add-bold',size:16}),b)))),
  h('section',{className:'s6',style:{border:'var(--dew-rule-dash)',padding:16,minHeight:420,background:s==='dragging'?'var(--dew-surface-alt)':undefined},'aria-label':'캔버스'},
   s==='empty'?Empty('+','빈 지면','왼쪽 블록을 끌어 놓거나 템플릿으로 시작하세요.',h(Button,{variant:'secondary'},'템플릿에서 시작')):
   h('div',{className:'g12',style:{gap:12}},blocks.map(([k,l,sp,ht])=>h('div',{key:k,className:sp,style:{height:ht,border:sel===k?'2px solid var(--dew-black)':'1px solid var(--dew-line)',background:k==='hero'?'var(--dew-grey-200)':'var(--dew-surface)',padding:12,display:'flex',flexDirection:'column',justifyContent:'space-between',opacity:s==='dragging'&&sel===k?.4:1}},h('span',{className:'dew-overline'},l),k==='title'&&h('span',{style:{font:'var(--dew-text-h3)'}},'저녁 여섯 시의 책방'))),
    s==='dragging'&&h('div',{className:'s12',style:{height:48,border:'2px solid var(--dew-action)',display:'grid',placeItems:'center'},className:'s12 dew-overline'},'여기에 놓기'))),
  h('aside',{className:'s3 stack','aria-label':'속성'},h('div',{className:'dew-overline',style:{borderTop:'var(--dew-rule)',paddingTop:12}},'INSPECTOR'),sel?h(F,null,h(TextField,{label:'제목 텍스트',defaultValue:'저녁 여섯 시의 책방'}),h(Select,{label:'서체',defaultValue:'d'},h('option',{value:'d'},'Display serif'),h('option',{value:'s'},'Sans')),h(Select,{label:'너비',defaultValue:'4'},h('option',{value:'4'},'4 / 12'),h('option',{value:'6'},'6 / 12'),h('option',{value:'8'},'8 / 12')),h(Switch,{label:'빨강 섹션 라벨 표시',defaultChecked:true})):h('p',{className:'dew-small dew-muted'},'블록을 선택하면 속성이 표시됩니다.'))))}
/* 09 modal */
function Modal({s}){const bg=h('div',{className:'stack',style:{opacity:.9}},h(Table,{caption:'9월 기사',columns:aCols(true).slice(0,-1),rows:arts.slice(0,4),rowKey:r=>r.id,minWidth:0}));
 const d=s==='dialog'?h(Dialog,{inline:true,title:'기사 공유 설정',description:'외부 공유 카드에 표시될 정보를 확인하세요.',footer:h(F,null,h(Button,{variant:'secondary'},'취소'),h(Button,null,'저장'))},h('div',{className:'stack'},h(TextField,{label:'공유 제목',defaultValue:'골목 끝, 불 켜진 서점'}),h(Textarea,{label:'요약',rows:3,defaultValue:'세 곳의 책방 주인과 보낸 가을 오후.'}))):h(AlertDialog,{inline:true,danger:true,previewState:s==='pending'?'pending':s==='error'?'error':undefined,title:'기사를 삭제할까요?',description:'“골목 끝, 불 켜진 서점”과 사진 12장이 함께 삭제되며 복구할 수 없습니다.',confirmLabel:'삭제',onConfirm(){}});
 return h(Shell,{active:'table',state:s},Head('ARCHIVE','기사',null),h('div',{className:'dew-stage',style:{minHeight:560,border:0,background:'transparent'}},bg,d))}
/* 10 empty */
function EmptyP({s}){const m={'first-run':['01','DEW 편집국에 오신 것을 환영합니다','첫 호를 만들고 필자를 초대하면 이 지면이 편집국 대시보드로 바뀝니다.',h(F,null,h(Button,null,'첫 호 만들기'),h(Button,{variant:'text'},'가이드 읽기'))],'no-results':['0','“극장 포스터”에 맞는 기사가 없습니다','철자를 확인하거나 필터를 해제하세요. 보관된 기사는 검색되지 않습니다.',h(Button,{variant:'secondary'},'필터 해제')],'no-access':['—','이 지면을 볼 권한이 없습니다','구독 관리는 편집장과 관리자만 볼 수 있습니다. 권한이 필요하면 편집장에게 요청하세요.',h(Button,{variant:'secondary'},'권한 요청')]}[s]||[];
 return h(Shell,{active:s==='no-results'?'table':s==='no-access'?'billing':'dashboard',state:s},s==='no-results'&&h('div',{style:{maxWidth:480}},h(TextField,{label:'검색',type:'search',defaultValue:'극장 포스터'})),h('div',{className:'g12'},h('div',{className:'s7'},Empty(...m)),s==='first-run'&&h('div',{className:'s5 dp-hide-sm'},Photo('WELCOME 4:5','4/5','light'))))}
const P={dashboard:[Dashboard,['default','loading','empty','error']],analytics:[Analytics,['default','loading','empty','error']],table:[TablePage,['default','loading','empty','error','long-text']],detail:[Detail,['default','loading','missing-data','error']],settings:[Settings,['default','saving','error','success']],billing:[Billing,['default','loading','error','empty']],chat:[Chat,['default','streaming','empty','error']],builder:[Builder,['default','selected','dragging','empty']],modal:[Modal,['dialog','confirm','pending','error']],empty:[EmptyP,['first-run','no-results','no-access']]};
window.DEW_PATTERNS=Object.fromEntries(Object.entries(P).map(([k,v])=>[k,v[1]]));
window.DEW_mountPattern=function(root,p,s){const e=P[p]||P.dashboard;const st=e[1].includes(s)?s:e[1][0];ReactDOM.createRoot(root).render(h(e[0],{s:st}));return {p:P[p]?p:'dashboard',s:st}};
})();
