const $=s=>document.querySelector(s), params=new URLSearchParams(location.search);
const stories=[
{category:'music',title:'새로운 소리가 시작되는 작은 공간',minutes:6,series:'Listening notes',art:'poster',body:'작은 공간을 채우는 리듬은 새로운 취향의 시작이 됩니다. 소리에 집중할 수 있는 시간과 장소를 상상해 봅니다.'},
{category:'stage',title:'무대 뒤에서 발견한 움직임',minutes:4,series:'Backstage',art:'stage-art',body:'무대를 완성하는 것은 눈에 보이는 장면만이 아닙니다. 움직임 사이의 여백과 준비하는 시간을 함께 바라봅니다.'},
{category:'culture',title:'밤의 도시를 기록하는 방법',minutes:5,series:'City walk',art:'collage',body:'밤이 되면 익숙한 거리도 다른 표정을 보여 줍니다. 빛과 그림자가 만드는 리듬을 천천히 기록합니다.'},
{category:'music',title:'한 곡을 오래 듣는 즐거움',minutes:3,series:'Listening notes',art:'',body:'한 곡을 반복해서 들을 때마다 작은 디테일이 새롭게 다가옵니다. 오늘은 배경의 소리 하나에 귀를 기울여 봅니다.'},
{category:'stage',title:'조명이 꺼진 뒤 남는 리허설의 리듬',minutes:7,series:'Backstage',art:'blue',body:'같은 동작을 반복하는 시간 속에서 새로운 장면을 발견합니다. 완성된 무대보다 준비하는 과정에 집중해 봅니다.'},
{category:'culture',title:'주말 골목에서 만난 작은 전시',minutes:2,series:'Weekend pick',art:'green',body:'멀리 떠나지 않아도 새로운 취향을 만날 수 있습니다. 익숙한 골목의 작은 전시를 상상하며 쓴 가상 이야기입니다.'}
];
const storageKey='kpop-v1-demo-1.5'; let state={saved:[],followed:false};let storageAvailable=true;
try{const parsed=JSON.parse(sessionStorage.getItem(storageKey)||'{}');state.saved=Array.isArray(parsed.saved)?parsed.saved.filter(i=>Number.isInteger(i)&&i>=0&&i<stories.length):[];state.followed=parsed.followed===true}catch{storageAvailable=false}
function persist(){try{sessionStorage.setItem(storageKey,JSON.stringify(state))}catch{storageAvailable=false}}
const allowed=['all','music','stage','culture'];let category=allowed.includes(params.get('category'))?params.get('category'):'all';let savedOnly=params.get('saved')==='1';
function storyCard(s,i){return `<a class="story" data-story="${i}" href="detail.html?story=${i}"><span class="thumb art ${s.art}" aria-hidden="true"></span><span><span class="eyebrow">${s.category}${state.saved.includes(i)?' · SAVED':''}</span><h3>${s.title}</h3><small>${s.minutes} min read · ${s.series}</small></span></a>`}
function renderFeed(){if(!$('#items'))return;const q=($('#search')?.value||'').trim().toLowerCase();const hits=stories.map((s,i)=>({s,i})).filter(({s,i})=>(category==='all'||s.category===category)&&(!savedOnly||state.saved.includes(i))&&`${s.title} ${s.category} ${s.series}`.toLowerCase().includes(q));$('#items').innerHTML=hits.map(({s,i})=>storyCard(s,i)).join('');$('#empty').hidden=hits.length>0;$('#empty').textContent=savedOnly?'저장한 이야기 중 일치하는 글이 없습니다. Explore에서 이야기를 찾아 저장해 보세요.':'일치하는 글이 없습니다. 검색어 또는 카테고리를 바꿔주세요.';$('#result-count').textContent=`${savedOnly?'Saved':'All stories'} · ${hits.length}개의 이야기`;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===category)));$('[data-saved-toggle]')?.setAttribute('aria-pressed',String(savedOnly));document.querySelectorAll('.bottomnav a').forEach(a=>{a.removeAttribute('aria-current');if((savedOnly&&a.href.includes('saved=1'))||(!savedOnly&&a.getAttribute('href')==='sub.html'))a.setAttribute('aria-current','page')});}
$('#search')?.addEventListener('input',renderFeed);document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;renderFeed()}));$('[data-saved-toggle]')?.addEventListener('click',()=>{savedOnly=!savedOnly;renderFeed()});$('#reset-filters')?.addEventListener('click',()=>{category='all';savedOnly=false;$('#search').value='';renderFeed();$('#search').focus()});renderFeed();
let id=Number(params.get('story')||0);if(!Number.isInteger(id)||id<0||id>=stories.length)id=0;const selected=stories[id];
function renderSave(){if(!$('#save'))return;const saved=state.saved.includes(id);$('#save').setAttribute('aria-pressed',String(saved));$('#save').classList.toggle('saved',saved);$('#save').textContent=saved?'✓ 저장됨 · 다시 눌러 해제':'＋ 이야기 저장';$('#save-status').textContent=storageAvailable?'이 탭에서 저장한 이야기는 화면을 이동해도 유지됩니다.':'브라우저 저장소를 사용할 수 없어 현재 화면에서만 유지됩니다.';}
if($('#story-title')){$('#story-title').textContent=selected.title;$('#story-category').textContent=`${selected.category.toUpperCase()} · ${selected.series}`;$('#reading-time').textContent=`${selected.minutes} min`;document.querySelector('.detailart').className=`detailart art ${selected.art}`;$('#article-body p').textContent=selected.body;renderSave()}
$('#save')?.addEventListener('click',()=>{state.saved=state.saved.includes(id)?state.saved.filter(n=>n!==id):[...state.saved,id];persist();renderSave()});
function renderFollow(){if(!$('#follow'))return;$('#follow').setAttribute('aria-pressed',String(state.followed));$('#follow').textContent=state.followed?'✓ 팔로잉':'팔로우';$('#follow-status').textContent=storageAvailable?'팔로우는 이 탭에만 저장되는 데모입니다.':'저장소를 사용할 수 없어 현재 화면에서만 유지됩니다.'}
if(params.get('view')==='creator'&&$('#creator-view')){$('#story-view').hidden=true;$('#creator-view').hidden=false;$('#creator-stories').innerHTML=stories.map((s,i)=>({s,i})).filter(({s})=>s.category==='culture').map(({s,i})=>storyCard(s,i)).join('');renderFollow()}
$('#follow')?.addEventListener('click',()=>{state.followed=!state.followed;persist();renderFollow()});
$('#sample-button')?.addEventListener('click',()=>{$('#sample-result').textContent='버튼이 활성화되었습니다.'});$('#retry')?.addEventListener('click',()=>{$('#retry-result').textContent='데모 재시도 완료 · 오류 상태가 해제되었습니다.'});
