import React,{useState} from 'react';
import {DialogExample,MenuExample,TableExample} from './composite-examples';
import {createRoot} from 'react-dom/client';
import {Button,TextField,Textarea,Select,Checkbox,Switch,Badge,Card,Skeleton,Icon} from '../../packages/ui/src/index';
import type {ButtonProps,IconName} from '../../packages/ui/src/index';
import components from '../../data/developer/components.json';
import comparison from '../../data/developer/comparison.json';
import icons from '../../data/developer/icons.json';
function App(){
 const [name,setName]=useState('Button'),[page,setPage]=useState('components'),[variant,setVariant]=useState<ButtonProps['variant']>('primary'),[size,setSize]=useState<ButtonProps['size']>('md'),[disabled,setDisabled]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(false),[text,setText]=useState(''),[checked,setChecked]=useState(false),[selected,setSelected]=useState('active'),[message,setMessage]=useState(''),[iconQuery,setIconQuery]=useState('');
 const component=components.find(c=>c.name===name)!;
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('복사했습니다.')}catch{setMessage('자동 복사가 지원되지 않습니다. 코드 영역을 선택해 복사하세요.')}}
 const change=(v:string)=>{setName(v);setError(false);setDisabled(false);setLoading(false);setText('');setChecked(false);setMessage('')};
 const examples:Record<string,React.ReactNode>={Dialog:<DialogExample/>,Menu:<MenuExample/>,Table:<TableExample/>,Button:<Button variant={variant} size={size} loading={loading} disabled={disabled} onClick={()=>setMessage('버튼 동작을 확인했습니다.')}>프로젝트 만들기</Button>,TextField:<TextField label="프로젝트 이름" description="40자 이내로 입력하세요." maxLength={40} error={error?'프로젝트 이름을 입력해 주세요.':undefined} disabled={disabled} value={text} onChange={e=>setText(e.target.value)}/>,Textarea:<Textarea label="프로젝트 설명" error={error?'설명을 입력해 주세요.':undefined} disabled={disabled} value={text} onChange={e=>setText(e.target.value)}/>,Select:<Select label="프로젝트 상태" value={selected} onChange={e=>setSelected(e.target.value)} disabled={disabled} error={error?'상태를 확인해 주세요.':undefined}><option value="active">진행 중</option><option value="done">완료</option></Select>,Checkbox:<Checkbox label="업데이트 받기" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={disabled}/>,Switch:<Switch label="알림 켜기" checked={checked} onChange={e=>setChecked(e.target.checked)} disabled={disabled}/>,Badge:<div className="row">{(['neutral','success','warning','error','info'] as const).map((tone,i)=><Badge key={tone} tone={tone}>{['기본','완료','주의','오류','안내'][i]}</Badge>)}</div>,Card:<Card title="이번 달 프로젝트" footer="최근 업데이트: 오늘"><p>진행 중인 프로젝트 12개</p></Card>,Skeleton:<div aria-busy="true" aria-label="콘텐츠를 불러오는 중"><Skeleton width={44} height={44} circle/><Skeleton height={24}/><Skeleton width="65%" height={16}/></div>,Icon:<div className="icon-grid">{Object.keys(icons.icons).filter(n=>n.includes(iconQuery)).map(n=><button key={n} className="icon-item" onClick={()=>copy(`<Icon name="${n}" />`)}><Icon name={n as IconName} size={24}/><span>{n}</span></button>)}</div>};
 let example=component.example;
 if(name==='Button')example=`<Button variant="${variant}" size="${size}"${disabled?' disabled':''}${loading?' loading':''}>프로젝트 만들기</Button>`;
 if(name==='TextField')example=`<TextField label="프로젝트 이름" maxLength={40}${disabled?' disabled':''}${error?' error="프로젝트 이름을 입력해 주세요."':''} />`;
 if(name==='Textarea')example=`<Textarea label="프로젝트 설명"${disabled?' disabled':''}${error?' error="설명을 입력해 주세요."':''} />`;
 if(name==='Select')example=`<Select label="프로젝트 상태" defaultValue="${selected}"${disabled?' disabled':''}${error?' error="상태를 확인해 주세요."':''}><option value="active">진행 중</option><option value="done">완료</option></Select>`;
 if(name==='Checkbox'||name==='Switch')example=`<${name} label="${name==='Checkbox'?'업데이트 받기':'알림 켜기'}"${checked?' defaultChecked':''}${disabled?' disabled':''} />`;
 const code=`import '@iak-design/ui/tokens.css';\nimport '@iak-design/ui/styles.css';\n${component.import}\n\nexport default function Example() {\n  return (${example});\n}`;
 const uiUrl=new URL('releases/iak-design-ui-0.6.0.tgz',location.href).href,mcpUrl=new URL('releases/iak-design-mcp-0.6.0.tgz',location.href).href;
 return <><header><a href="../#overview">IAK <span>Design Studio</span></a><nav aria-label="개발 가이드">{[['components','컴포넌트'],['comparison','원티드 비교'],['setup','설치 · AI/MCP']].map(([key,label])=><button key={key} onClick={()=>{setPage(key);setMessage('')}} aria-pressed={page===key}>{label}</button>)}</nav><span className="version">0.6 · Preview</span></header><div className="dev-shell">{page==='components'&&<aside aria-label="컴포넌트 목록">{components.map(c=><button key={c.name} onClick={()=>change(c.name)} aria-pressed={name===c.name}><span>{c.name}</span><small>{c.group}</small></button>)}<a href="../#assets">원본 디자인 자산 ↗</a></aside>}<main>
 {page==='components'&&<><p className="eyebrow">IAK REACT / {component.group}</p><h1>{name}</h1><p className="lead">{component.description}</p><p className="muted">실제 @iak-design/ui 컴포넌트를 렌더링합니다. Montage의 API를 복제한 제품이 아닌 IAK 자체 구현입니다.</p><section className="panel"><h2>Playground</h2><div className="controls">{name==='Button'&&<><Select label="버튼 유형" value={variant} onChange={e=>setVariant(e.target.value as ButtonProps['variant'])}>{['primary','secondary','danger','text'].map(v=><option key={v}>{v}</option>)}</Select><Select label="버튼 크기" value={size} onChange={e=>setSize(e.target.value as ButtonProps['size'])}>{['sm','md','lg'].map(v=><option key={v}>{v}</option>)}</Select><Checkbox label="로딩 상태" checked={loading} onChange={e=>setLoading(e.target.checked)}/></>}{['Button','TextField','Textarea','Select','Checkbox','Switch'].includes(name)&&<Checkbox label="비활성화 상태" checked={disabled} onChange={e=>setDisabled(e.target.checked)}/ >}{['TextField','Textarea','Select'].includes(name)&&<Checkbox label="오류 상태" checked={error} onChange={e=>setError(e.target.checked)}/ >}{name==='Icon'&&<TextField label="아이콘 검색" value={iconQuery} onChange={e=>setIconQuery(e.target.value)}/>}</div><div className="live-example" aria-label="실행 예제">{examples[name]}</div>{['TextField','Textarea'].includes(name)&&<p className="muted">입력한 값: {text||'(비어 있음)'}</p>}{['Checkbox','Switch'].includes(name)&&<p className="muted">현재 상태: {checked?'켜짐':'꺼짐'}</p>}</section><section className="panel"><div className="section-heading"><h2>사용 코드</h2><Button variant="secondary" onClick={()=>copy(code)}>코드 복사</Button></div><pre><code>{code}</code></pre></section><section className="panel"><h2>Props</h2><div className="table-wrap"><table><thead><tr><th>이름</th><th>타입</th><th>기본값</th><th>설명</th></tr></thead><tbody>{component.props.map(p=><tr key={p.name}><td><code>{p.name}</code></td><td><code>{p.type}</code></td><td>{p.default}</td><td>{p.description}</td></tr>)}</tbody></table></div><p className="muted">{['Dialog','Menu','Table'].includes(name)?'복합 컴포넌트는 위 API로 구성합니다. cell·children·footer에 필요한 UI를 전달하세요.':'표에 없는 속성은 해당 HTML 요소의 React 속성 타입을 따릅니다.'}</p></section><section className="panel"><h2>접근성과 동작</h2><ul>{component.accessibility.map(s=><li key={s}>{s}</li>)}</ul></section>{name==='Icon'&&<section className="panel"><h2>아이콘 출처</h2><p>Eva Icons · Akveo · MIT / Solar · 480 Design · CC BY 4.0. 원본 SVG 중 일부를 수정 없이 사용합니다. <a href="icon-licenses.json">저작자·라이선스 보기</a></p><h2>원본에서 해결되지 않은 9개 이름</h2><p>다른 아이콘으로 임의 대체하지 않았습니다. 패키지는 아래 이름을 허용하지 않습니다.</p><pre>{icons.unresolved.join('\n')}</pre></section>}</>}
 {page==='comparison'&&<><p className="eyebrow">WANTED MONTAGE BENCHMARK</p><h1>어디까지 갖췄는지, 명확하게.</h1><p className="lead">원티드의 제품 구성 기준으로 IAK의 이전 상태·이번 구현·남은 작업을 나눴습니다.</p><div className="notice">비교일 {comparison.checkedAt} · 공식 문서와 공개 저장소 기준. 이번 세션에서 원티드 MCP 실시간 호출은 확인하지 못했습니다.</div>{comparison.items.map(item=><section className="panel" key={item.area}><div className="section-heading"><h2>{item.area}</h2><Badge tone={item.status==='구현'?'success':item.status==='부분 구현'?'warning':'neutral'}>{item.status}</Badge></div><dl><dt>원티드</dt><dd>{item.wanted}</dd><dt>IAK 이전</dt><dd>{item.before}</dd><dt>이번 구현</dt><dd>{item.now}</dd><dt>남은 작업</dt><dd>{item.remaining}</dd></dl></section>)}<section className="panel"><h2>확인한 공식 출처</h2><ul>{comparison.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener">{s.title} ↗</a></li>)}</ul></section></>}
 {page==='setup'&&<><p className="eyebrow">DEVELOPER / AI</p><h1>프로젝트에 설치해서 사용하세요.</h1><p className="lead">UI 패키지와 MCP는 버전별 설치 파일로 제공합니다. npm registry에는 아직 정식 발행하지 않았습니다.</p><section className="panel"><h2>01 · React UI</h2><p>React 18에서 검증한 Preview입니다. React 19는 별도 검증이 필요합니다. CSS 토큰·폰트·아이콘을 함께 받습니다. Dialog/Menu의 동작에는 Radix 의존성이 설치됩니다.</p><pre>npm install {uiUrl}</pre><Button onClick={()=>copy(`npm install ${uiUrl}`)}>UI 설치 명령 복사</Button><pre>{`import '@iak-design/ui/tokens.css';\nimport '@iak-design/ui/styles.css';\nimport { Button, TextField } from '@iak-design/ui';`}</pre></section><section className="panel"><h2>02 · IAK 전용 MCP</h2><p>Node 20 이상. 읽기 전용 로컬 stdio 서버입니다. 사이트를 여는 것만으로 AI 도구에 등록되지는 않습니다.</p><pre>npm install -g {mcpUrl}</pre><Button variant="secondary" onClick={()=>copy(`npm install -g ${mcpUrl}`)}>MCP 설치 명령 복사</Button><h3>Claude Code</h3><pre>claude mcp add iak-design-system -- iak-design-mcp</pre><h3>Codex</h3><pre>codex mcp add iak-design-system -- iak-design-mcp</pre><p>Codex 터미널에서 실행한 뒤 앱의 MCP 연결 상태를 확인하세요.</p><h3>일반 MCP 클라이언트 설정</h3><pre>{JSON.stringify({mcpServers:{'iak-design-system':{command:'iak-design-mcp',args:[]}}},null,2)}</pre><p>컴포넌트·props·토큰·아이콘·가이드·자산·템플릿을 조회하는 10개 도구. 파일 수정이나 외부 API 호출 기능은 없습니다.</p></section><section className="panel"><h2>03 · SKILL 갱신</h2><p>기존 설치 명령으로 최신 SKILL.md를 받습니다. UI/MCP 패키지는 위 명령으로 별도 설치·업데이트합니다.</p><a href="../#start">스킬 설치 안내 ↗</a></section><section className="panel"><h2>아직 제공하지 않는 것</h2><p>DatePicker, Toast 관리, 테이블 페이지네이션·가상화, 라이트 테마, Next.js 전용 통합, npm 정식 발행, 원격 MCP 서버는 남은 작업입니다.</p></section></>}
 <p className="muted"><a href="THIRD_PARTY_NOTICES.txt">오픈소스 라이선스</a></p><p role="status" className="status">{message}</p></main></div></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
