/* ZEM_V1 · 10 patterns — ZEM-style DERIVED extensions (not claimed to exist in the source). Fictional, self-written sample data only. */
(function(){
const h=React.createElement,F=React.Fragment;
const {Icon,Button,TextField,Textarea,Select,Checkbox,Switch,Badge,Card,Skeleton,Dialog,Menu,Table,Pagination,AlertDialog}=ZEM;const TV=ZEM.preview.ToastView;
/* ---------- data ---------- */
const days=['월','화','수','목','금','토','일'];
const usage=[92,78,105,64,88,140,120],goal=90;
const kids=['민서','도윤'];
const MN=['줄넘기 100번','영어 단어 20개 외우기','방 정리하기','독서 20분','수학 학습지 2장','화분에 물 주기','피아노 연습 30분','가족에게 편지 쓰기','일기 쓰기','신발 정리하기','자전거 타기 20분','동생과 보드게임'];
const ST=['진행 중','확인 대기','완료','놓침'],TONE={'진행 중':'info','확인 대기':'warning','완료':'success','놓침':'error'};
const missions=MN.map((n,i)=>({id:'M-'+(101+i),name:n,kid:i%5===4?null:kids[i%2],status:ST[i%4],due:'9월 '+(22+i%7)+'일',point:i%6===5?null:(i%4+1)*50}));
const miss=(v,t)=>v==null||v===''?h('span',{className:'miss'},t||'—'):v;
const pt=v=>v==null?h('span',{className:'miss'},'미정'):v+'P';
/* ---------- charts (progress/data role = periwinkle) ---------- */
function Bars({data,labels,height=160,a11y,line}){const W=600,H=height,max=Math.max(...data,line||0)*1.15,bw=W/labels.length;return h('svg',{className:'chart',viewBox:`0 0 ${W} ${H+24}`,role:'img','aria-label':a11y},
 line&&h('line',{x1:0,x2:W,y1:H-line/max*H,y2:H-line/max*H,stroke:'var(--zem-coral-600)',strokeDasharray:'6 6',strokeWidth:2}),
 labels.map((l,i)=>{const v=data[i],bh=v/max*H,over=line&&v>line;return h('g',{key:l},h('rect',{x:i*bw+bw*.25,y:H-bh,width:bw*.5,height:bh,rx:10,fill:over?'var(--zem-periwinkle-300)':'var(--zem-periwinkle-500)'}),h('text',{x:i*bw+bw/2,y:H+18,textAnchor:'middle',fill:'var(--zem-fg-2)',fontSize:13,fontWeight:700},l))}))}
const Legend=items=>h('div',{className:'legend'},items.map(([c,l])=>h('span',{key:l},h('i',{style:{background:c}}),l)));
/* ---------- shell ---------- */
const NAV=[['dashboard','홈','eva:home-fill'],['analytics','리포트','solar:chart-2-bold'],['table','미션','solar:checklist-bold'],['builder','일정','eva:calendar-fill'],['chat','채팅','solar:chat-round-line-bold'],['billing','요금제','solar:card-bold'],['settings','설정','solar:settings-bold']];
const TABS=[['dashboard','홈','eva:home-fill'],['builder','일정','eva:calendar-fill'],['table','미션','solar:checklist-bold'],['settings','더보기','eva:more-horizontal-fill']];
function Shell({active,title,hero,sub,children,state,back}){return h('div',{className:'zs'},
 h('nav',{className:'zs-rail','aria-label':'주 메뉴'},h('div',{className:'wm'},'ZEM_V1'),NAV.map(([k,l,ic])=>h('a',{key:k,href:`?p=${k}&s=default`,'aria-current':active===k?'page':undefined},h(Icon,{name:ic,size:22}),h('span',null,l)))),
 h('div',{className:'zs-main'},
  h('header',{className:'zs-header'},h('div',{className:'zs-top'},back?h('a',{className:'zs-ib',href:'?p=table&s=default','aria-label':'뒤로'},h(Icon,{name:'eva:arrow-ios-back-fill',size:24})):h('span',{className:'zs-ib','aria-hidden':'true'}),h('div',{className:'grow'},title),h('button',{type:'button',className:'zs-ib','aria-label':'알림 2개'},h(Icon,{name:'solar:bell-bold',size:22}),h('span',{className:'zs-dot'}))),
   h('div',{className:'zs-hero'},h('span',{className:'zs-chip'},h('i',null,'민'),'민서 · 초등 3학년'),hero&&h('h1',null,hero),sub&&h('p',null,sub))),
  h('main',{className:'zs-body','data-state':state},children)),
 h('nav',{className:'zs-tabbar','aria-label':'하단 탭'},TABS.map(([k,l,ic])=>h('a',{key:k,href:`?p=${k}&s=default`,'aria-current':active===k?'page':undefined},h(Icon,{name:ic,size:24}),l))));}
const Err=(t,msg,retry=true)=>h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',{className:'stack',style:{gap:6,flex:1}},h('b',null,t),h('span',{className:'muted'},msg),retry&&h('div',null,h(Button,{variant:'secondary',size:'sm'},h(Icon,{name:'eva:refresh-fill',size:16}),'다시 시도'))));
const Empty=(icon,t,d,action)=>h('div',{className:'empty'},h('div',{className:'plate'},h(Icon,{name:icon,size:32})),h('h2',null,t),h('p',null,d),action&&h('div',{className:'row',style:{justifyContent:'center'}},action));
const SkCard=(cls,big)=>h('div',{className:cls},h(Card,{'aria-busy':'true'},h(Skeleton,{height:16,width:'45%'}),h(Skeleton,{height:28,width:'70%'}),big&&h(Skeleton,{height:140})));
const Row=(tile,ic,t,s,right)=>h('li',{key:t},h('span',{className:'tile '+tile},h(Icon,{name:ic,size:20})),h('div',{className:'t'},h('b',null,t),h('span',null,s)),right);
const Done=k=>h('span',{className:'done'+(k==='todo'?' todo':k==='lime'?' lime':''),'aria-label':k==='todo'?'미완료':'완료'},h(Icon,{name:k==='todo'?'eva:arrow-ios-forward-fill':'eva:checkmark-fill',size:16}));
const mCols=compact=>[{id:'name',header:'미션',cell:r=>h('a',{href:'?p=detail&s=default'},r.name),sortValue:r=>r.name},{id:'kid',header:'자녀',cell:r=>miss(r.kid,'미지정')},{id:'status',header:'상태',cell:r=>h(Badge,{tone:TONE[r.status]},r.status),sortValue:r=>r.status},...(compact?[]:[{id:'due',header:'마감',cell:r=>r.due,sortValue:r=>r.due},{id:'point',header:'보상',cell:r=>pt(r.point),sortValue:r=>r.point,align:'right'}]),{id:'act',header:'',align:'right',cell:r=>h(Menu,{label:r.name+' 작업',trigger:h(Button,{variant:'text',size:'sm','aria-label':r.name+' 작업'},h(Icon,{name:'eva:more-horizontal-fill',size:20})),items:[{id:'edit',label:'수정',onSelect(){}},{id:'done',label:'완료 확인',onSelect(){}},{id:'del',label:'삭제',danger:true,separatorBefore:true,onSelect(){}}]})}];
/* ---------- screens ---------- */
const S={};
S.dashboard={label:'Dashboard',states:['default','loading','empty','error'],render(s){
 return h(Shell,{active:'dashboard',title:'홈',hero:s==='empty'?'아직 오늘 일정이 없어요':'지금은 자유 시간이에요',sub:s==='empty'?'일정과 미션을 추가해 보세요':'오후 3:00 – 4:30 · 34분 남음',state:s},
  s==='error'&&Err('기기 상태를 불러오지 못했어요','민서의 휴대폰이 오프라인이에요. 마지막 동기화 오후 2:48.'),
  s==='loading'?h('div',{className:'zs-grid','aria-busy':'true','aria-label':'홈을 불러오는 중'},SkCard('t4 d4'),SkCard('t4 d4'),SkCard('t8 d4'),SkCard('t8 d8',true),SkCard('t8 d4',true)):
  s==='empty'?h(F,null,h(Card,null,h('div',{className:'row between'},h('div',{className:'stack',style:{gap:4}},h('b',{style:{font:'var(--zem-text-title)'}},'자유 모드'),h('span',{className:'muted cap'},'제한 없이 사용 중')),h('span',{className:'tile soft'},h(Icon,{name:'solar:clock-circle-bold',size:20})))),Empty('eva:calendar-fill','오늘 일정이 비어 있어요','학원·숙제·놀이 시간을 추가하면 이곳에 순서대로 보여요.',h(F,null,h(Button,null,h(Icon,{name:'eva:plus-fill',size:18}),'일정 추가'),h(Button,{variant:'secondary'},'미션 만들기')))):
  h('div',{className:'zs-grid'},
   h('div',{className:'t8 d4'},h(Card,null,h('div',{className:'row between'},h('div',{className:'stack',style:{gap:4}},h('b',{style:{font:'var(--zem-text-h2)'}},'자유 시간'),h('span',{className:'muted cap'},'오후 3:00 – 4:30')),h('span',{className:'tile peri'},h(Icon,{name:'solar:clock-circle-bold',size:20}))),h('div',{className:'prog',role:'progressbar','aria-valuenow':62,'aria-valuemin':0,'aria-valuemax':100,'aria-label':'자유 시간 경과'},h('i',{style:{width:'62%'}})),h('div',{className:'row between cap'},h('span',{className:'muted'},'56분 사용'),h('b',null,'34분 남음')))),
   h('div',{className:'t4 d4'},h(Card,{title:'이번 주 미션'},h('div',{className:'kpi'},'3 / 5'),h('div',{className:'prog'},h('i',{style:{width:'60%'}})),h('span',{className:'muted cap'},'보상 150P 적립'))),
   h('div',{className:'t4 d4'},h(Card,{title:'오늘 사용 시간'},s==='error'?h(F,null,h('div',{className:'kpi miss'},'—'),h('span',{className:'muted cap'},'동기화 실패')):h(F,null,h('div',{className:'kpi'},'1시간 28분'),h(Badge,{tone:'success'},'목표 이내')))),
   h('div',{className:'t8 d8'},h(Card,{title:'오늘 일정'},h('ul',{className:'rows'},Row('cyan','eva:calendar-fill','수학 학원','오후 1:00 – 2:30',Done('done')),Row('peri','solar:clock-circle-bold','자유 시간','오후 3:00 – 4:30',h(Badge,{tone:'info'},'지금')),Row('violet','solar:book-bold','영어 학원','오후 5:00 – 6:00',Done('todo')),Row('lime','solar:target-bold','미션 · 줄넘기 100번','오늘까지 · 50P',Done('lime'))))),
   h('div',{className:'t8 d4'},h(Card,{title:'이번 주 사용 (분)',footer:Legend([['var(--zem-periwinkle-500)','목표 이내'],['var(--zem-periwinkle-300)','목표 초과'],['var(--zem-coral-600)','목표 90분']])},h(Bars,{data:usage,labels:days,line:goal,a11y:'요일별 사용 시간, 토요일 140분 최고, 목표 90분'})))));}};
S.analytics={label:'Analytics',states:['default','loading','empty','error'],render(s){
 const cats=[['학습',38,'cyan'],['동영상',27,'peri'],['게임',18,'violet'],['메시지',12,'mint'],['기타',5,'soft']];
 return h(Shell,{active:'analytics',title:'사용 리포트',hero:'이번 주 리포트',sub:'9월 22일 – 28일',state:s},
  h(Card,null,h('div',{className:'zs-grid'},h('div',{className:'m2 t3 d3'},h(Select,{label:'기간',defaultValue:'w'},h('option',{value:'w'},'이번 주'),h('option',null,'지난 4주'))),h('div',{className:'m2 t3 d3'},h(Select,{label:'자녀',defaultValue:s==='empty'?'d':'m'},h('option',{value:'m'},'민서'),h('option',{value:'d'},'도윤 (새 기기)'))))),
  s==='error'?Err('리포트를 만들지 못했어요','집계 서버 응답이 늦어요. 잠시 후 다시 시도해 주세요.'):
  s==='empty'?Empty('solar:chart-2-bold','아직 리포트가 없어요','도윤의 기기는 어제 연결되었어요. 하루 이상 사용 기록이 쌓이면 리포트가 만들어져요.',h(Button,{variant:'secondary'},'민서 리포트 보기')):
  s==='loading'?h('div',{className:'zs-grid','aria-busy':'true'},SkCard('t8 d8',true),SkCard('t8 d4',true),SkCard('t8 d12',true)):
  h('div',{className:'zs-grid'},h('div',{className:'t8 d8'},h(Card,{title:'요일별 사용 시간 (분)'},h(Bars,{data:usage,labels:days,line:goal,a11y:'주간 사용 시간'}),h('div',{className:'row between cap'},h('span',{className:'muted'},'하루 평균'),h('b',{className:'num'},'98분')))),
   h('div',{className:'t8 d4'},h(Card,{title:'앱 종류별'},h('div',{className:'stack g16'},cats.map(([l,v,c])=>h('div',{key:l,className:'row',style:{flexWrap:'nowrap'}},h('span',{className:'tile '+c,style:{width:32,height:32,borderRadius:8}},h(Icon,{name:'solar:smartphone-bold',size:16})),h('div',{className:'stack',style:{gap:6,flex:1}},h('div',{className:'row between'},h('span',null,l),h('b',{className:'num'},v+'%')),h('div',{className:'prog',role:'img','aria-label':l+' '+v+'%'},h('i',{style:{width:v+'%'}})))))))),
   h('div',{className:'t8 d12'},h(Table,{caption:'자주 쓴 앱',minWidth:420,defaultSort:{columnId:'min',direction:'descending'},rowKey:r=>r.a,rows:[{a:'단어 퀴즈',c:'학습',min:142},{a:'동영상 앱',c:'동영상',min:118},{a:'블록 퍼즐',c:'게임',min:86},{a:'가족 메신저',c:'메시지',min:54},{a:'그림판',c:null,min:21}],columns:[{id:'a',header:'앱',cell:r=>r.a,sortValue:r=>r.a},{id:'c',header:'종류',cell:r=>miss(r.c,'분류 없음')},{id:'min',header:'사용(분)',cell:r=>r.min,sortValue:r=>r.min,align:'right'}]}))));}};
S.table={label:'Table',states:['default','loading','empty','error','long-text'],render(s){
 const rows=s==='empty'?[]:s==='long-text'?[{...missions[0],name:'토요일 오전에 할머니 댁 가기 전까지 방 정리하고 장난감 상자 세 개를 종류별로 나누어 담기',kid:null,point:null},...missions.slice(1,6)]:missions;
 return h(Shell,{active:'table',title:'미션',hero:'미션 목록',sub:rows.length+'개 · 이번 주',state:s},
  h(Card,null,h('div',{className:'zs-grid'},h('div',{className:'t4 d6'},h(TextField,{label:'검색',type:'search',placeholder:'미션 이름',defaultValue:s==='empty'?'수영장':''})),h('div',{className:'m2 t2 d3'},h(Select,{label:'상태'},h('option',null,'전체'),ST.map(x=>h('option',{key:x},x)))),h('div',{className:'m2 t2 d3'},h(Select,{label:'자녀'},h('option',null,'전체'),kids.map(k=>h('option',{key:k},k)))))),
  h('div',{className:'row between'},h('b',null,'전체 미션'),h(Button,{size:'sm'},h(Icon,{name:'eva:plus-fill',size:16}),'미션 추가')),
  h(Table,{caption:'미션 목록',columns:mCols(false),rows,rowKey:r=>r.id,loading:s==='loading',error:s==='error'?'미션을 불러오지 못했어요. 네트워크 상태를 확인해 주세요.':undefined,emptyMessage:'“수영장”과 일치하는 미션이 없어요.',pagination:{pageSize:6},minWidth:640}));}};
S.detail={label:'Detail',states:['default','loading','missing-data','error'],render(s){
 const m=s==='missing-data',p=missions[m?4:0];
 if(s==='error')return h(Shell,{active:'table',title:'미션 상세',back:true,state:s},Empty('solar:shield-warning-bold','이 미션을 볼 수 없어요','다른 보호자가 만든 비공개 미션이에요. 보호자 권한을 요청해 주세요.',h(Button,{variant:'secondary'},'권한 요청')));
 return h(Shell,{active:'table',title:'미션 상세',back:true,hero:s==='loading'?null:p.name,sub:s==='loading'?null:p.id+' · 9월 20일 생성',state:s},
  s==='loading'?h('div',{className:'zs-grid','aria-busy':'true'},SkCard('t8 d8',true),SkCard('t8 d4',true)):h(F,null,
  h('div',{className:'row'},h(Badge,{tone:TONE[p.status]},p.status),m?h(Badge,{tone:'warning'},h(Icon,{name:'eva:alert-triangle-fill',size:14}),'필수 정보 2개 없음'):h(Badge,null,'마감 '+p.due)),
  h('div',{className:'zs-grid'},h('div',{className:'t8 d8'},h(Card,{title:'미션 정보',footer:h('div',{className:'row',style:{justifyContent:'flex-end'}},h(Button,{variant:'secondary'},h(Icon,{name:'eva:edit-fill',size:16}),'수정'),h(Button,null,'완료 확인'))},h('dl',{className:'dl'},h('dt',null,'자녀'),h('dd',null,miss(m?null:p.kid,'미지정')),h('dt',null,'보상'),h('dd',null,pt(m?null:p.point)),h('dt',null,'마감'),h('dd',null,p.due+' 오후 8:00'),h('dt',null,'인증 방법'),h('dd',null,'사진 1장'),h('dt',null,'메모'),h('dd',null,m?miss(null,'메모가 없어요. 수정에서 추가하세요.'):'앞마당에서 쉬지 않고 100번! 중간에 쉬면 처음부터 다시 세기로 했어요.')))),
   h('div',{className:'t8 d4'},h(Card,{title:'진행률'},h('div',{className:'kpi'},m?'0%':'70%'),h('div',{className:'prog'},h('i',{style:{width:m?'0%':'70%'}})),h('span',{className:'muted cap'},m?'기록이 아직 없어요':'주 5회 중 3.5회 달성'))),
   h('div',{className:'t8 d12'},h(Card,{title:'기록'},m?h('p',{className:'muted'},'기록된 활동이 없어요.'):h('ul',{className:'rows'},Row('mint','eva:checkmark-fill','사진 인증 올림','민서 · 오늘 오후 4:12',null),Row('soft','solar:chat-round-line-bold','“내일은 120번 할래요!”','민서 · 어제 저녁 7:40',null),Row('peri','eva:plus-fill','미션 생성','엄마 · 9월 20일',null)))))));}};
S.settings={label:'Settings',states:['default','saving','error','success'],render(s){
 const e=s==='error',d=s==='saving';
 return h(Shell,{active:'settings',title:'설정',hero:'민서의 기기 설정',sub:'사용 시간 · 알림 · 기본 정보',state:s},
  e&&h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',null,h('b',null,'2개 항목을 확인해 주세요'),h('div',{className:'muted'},'오류가 있는 칸을 고친 뒤 다시 저장하세요.'))),
  h('div',{className:'zs-grid'},h('div',{className:'t8 d7'},h(Card,{title:'기본 정보',footer:h('div',{className:'row',style:{justifyContent:'flex-end'}},h(Button,{variant:'secondary',disabled:d},'취소'),h(Button,{loading:d},'저장'))},
    h('div',{className:'stack g16'},h(TextField,{label:'자녀 이름',defaultValue:e?'':'민서',required:true,error:e?'이름을 입력해 주세요.':undefined,disabled:d}),h(TextField,{label:'하루 사용 목표 (분)',type:'number',defaultValue:e?'-10':'90',error:e?'1분 이상으로 입력해 주세요.':undefined,description:e?undefined:'목표를 넘으면 보호자에게 알려요.',disabled:d}),h(Select,{label:'잠자기 모드 시작',defaultValue:'21',disabled:d},h('option',{value:'21'},'오후 9:00'),h('option',{value:'22'},'오후 10:00')),h(Textarea,{label:'메모',rows:3,defaultValue:'주말에는 30분 더 허용.',disabled:d})))),
   h('div',{className:'t8 d5'},h(Card,{title:'알림'},h('div',{className:'stack',style:{gap:2}},h(Switch,{label:'목표 시간 초과 알림',defaultChecked:true,disabled:d}),h(Switch,{label:'미션 인증 도착 알림',defaultChecked:true,disabled:d}),h(Switch,{label:'주간 리포트 받기',disabled:d}),h(Checkbox,{label:'밤 10시 이후 알림 끄기',defaultChecked:true,disabled:d}))))),
  s==='success'&&h('ol',{className:'zem-toast-viewport'},h(TV,{tone:'success',title:'설정을 저장했어요',description:'민서의 기기에 바로 적용돼요.'})));}};
S.billing={label:'Billing',states:['default','loading','error','empty'],render(s){
 const inv=s==='empty'?[]:[['B-0925','9월 25일',4900,'결제 완료'],['B-0825','8월 25일',4900,'결제 완료'],['B-0725','7월 25일',4900,'결제 완료'],['B-0625','6월 25일',0,'무료 체험']].map(([id,d,a,st])=>({id,d,a,st}));
 return h(Shell,{active:'billing',title:'요금제',hero:'가족 요금제',sub:'월 4,900원 · 자녀 2명 (가상)',state:s},
  s==='error'&&h('div',{className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'solar:danger-triangle-bold'})),h('div',{className:'stack',style:{gap:6,flex:1}},h('b',null,'10월 자동 결제에 실패했어요'),h('span',{className:'muted'},'등록한 카드(가상) •••• 1234의 유효기간이 지났어요. 10월 2일까지 바꾸지 않으면 리포트 기능이 멈춰요.'),h('div',null,h(Button,{size:'sm'},'결제 수단 변경')))),
  s==='loading'?h('div',{className:'zs-grid','aria-busy':'true'},SkCard('t8 d5',true),SkCard('t8 d7',true),SkCard('t8 d12',true)):
  h('div',{className:'zs-grid'},h('div',{className:'t8 d5'},h(Card,{title:'현재 요금제',footer:'다음 결제일 10월 25일'},h('div',{className:'row between'},h('div',null,h('div',{className:'kpi'},'가족'),h('span',{className:'muted'},'월 4,900원')),h(Badge,{tone:s==='error'?'error':'success'},s==='error'?'결제 실패':'이용 중')),h('div',{className:'row'},h(Button,{variant:'secondary'},'요금제 변경'),h(Button,{variant:'text'},'해지 안내')))),
   h('div',{className:'t8 d7'},h(Card,{title:'이번 달 포인트'},h('div',{className:'stack g16'},[['미션 보상 지급','750 / 1,000P',75],['선물 교환','2 / 3회',66],['사진 인증 저장','4.6 / 5GB',92]].map(([l,v,p])=>h('div',{key:l,className:'stack',style:{gap:6}},h('div',{className:'row between'},h('span',null,l),h('span',{className:'num strong'},v,p>=90&&h(Badge,{tone:'warning',style:{marginLeft:8}},'거의 다 씀'))),h('div',{className:'prog'},h('i',{style:{width:p+'%'}}))))))),
   h('div',{className:'t8 d12'},h(Table,{caption:'결제 내역',minWidth:480,rows:inv,rowKey:r=>r.id,emptyMessage:'아직 결제 내역이 없어요. 첫 결제는 무료 체험이 끝나는 10월 25일이에요.',columns:[{id:'id',header:'번호',cell:r=>r.id},{id:'d',header:'날짜',cell:r=>r.d},{id:'a',header:'금액',cell:r=>r.a.toLocaleString('ko-KR')+'원',align:'right',sortValue:r=>r.a},{id:'st',header:'상태',cell:r=>h(Badge,{tone:r.st==='무료 체험'?'info':'success'},r.st)}]}))));}};
S.chat={label:'AI Chat',states:['default','streaming','empty','error'],render(s){
 const log=s==='empty'?null:[h('div',{key:1,className:'bubble me'},'민서 이번 주 일정 중에 빈 시간 알려줘.'),h('div',{key:2,className:'bubble'},'수요일 오후 3시–5시, 금요일 오후 4시 이후가 비어 있어요. 수요일에는 영어 단어 미션을 넣어 볼까요?'),h('div',{key:3,className:'bubble me'},'금요일에 줄넘기 미션 추가해 줘.'),
  s==='streaming'?h('div',{key:4,className:'bubble',role:'status','aria-live':'polite'},'금요일 오후 4:30에 “줄넘기 100번” 미션을 만들고 있어요. 보상은 '):s==='error'?h('div',{key:4,className:'banner',role:'alert'},h('span',{className:'ic'},h(Icon,{name:'eva:alert-circle-outline'})),h('div',{className:'stack',style:{gap:6}},h('span',null,'답변을 만들지 못했어요. 입력한 내용은 그대로 있어요.'),h('div',null,h(Button,{variant:'secondary',size:'sm'},h(Icon,{name:'eva:refresh-fill',size:16}),'다시 시도')))):h('div',{key:4,className:'bubble'},'금요일 오후 4:30 “줄넘기 100번” 미션을 추가했어요. 보상은 50P로 설정했어요.')];
 return h(Shell,{active:'chat',title:'일정 도우미',hero:s==='empty'?'무엇을 도와드릴까요?':'일정 도우미',sub:'가상 예시 대화 · 실제 AI에 연결되어 있지 않아요',state:s},
  h('div',{className:'chat'},h('div',{className:'threads'},h(Card,{title:'대화'},h(Button,{variant:'secondary',size:'sm'},h(Icon,{name:'eva:plus-fill',size:16}),'새 대화'),h('ul',{className:'rows'},['이번 주 빈 시간','주말 가족 일정','미션 보상 정하기'].map((t,i)=>h('li',{key:t},h('a',{href:'#',style:{color:i===0&&s!=='empty'?'var(--zem-action)':'var(--zem-fg)',fontWeight:700,textDecoration:'none'}},t)))))),
   h(Card,null,h('div',{className:'stack g20',style:{minHeight:360}},s==='empty'?h('div',{className:'stack',style:{alignItems:'center',textAlign:'center',padding:'32px 0',gap:14}},h('div',{className:'empty',style:{padding:0,boxShadow:'none'}},h('div',{className:'plate'},h(Icon,{name:'solar:chat-round-line-bold',size:32}))),h('p',{className:'muted'},'일정, 미션, 사용 시간에 대해 물어보세요.'),h('div',{className:'row',style:{justifyContent:'center'}},['오늘 일정 요약','빈 시간 찾기','미션 추천'].map(t=>h(Button,{key:t,variant:'secondary',size:'sm'},t)))):h('div',{className:'chat-log'},log),
    h('div',{className:'stack',style:{gap:8}},h(Textarea,{label:'메시지',rows:2,placeholder:'질문을 입력하세요',disabled:s==='streaming'}),h('div',{className:'row between'},h('span',{className:'muted cap'},'답변이 정확하지 않을 수 있어요.'),s==='streaming'?h(Button,{variant:'secondary'},'멈추기'):h(Button,null,'보내기')))))));}};
S.builder={label:'Builder',states:['default','selected','dragging','empty'],render(s){
 const blocks=s==='empty'?[]:[['b1','cyan','eva:calendar-fill','수학 학원','월·수 오후 1:00'],['b2','violet','solar:book-bold','독서 20분','매일 저녁 8:00'],['b3','lime','solar:target-bold','줄넘기 미션','금 오후 4:30'],['b4','peri','solar:moon-bold','잠자기 모드','매일 오후 9:00']];
 const sel=s==='selected'||s==='dragging'?'b3':null;
 return h(Shell,{active:'builder',title:'일정',hero:'주간 일정 만들기',sub:'초안 · 오후 3:40 자동 저장',state:s},
  h('div',{className:'row'},h(Button,{variant:'secondary',size:'sm'},h(Icon,{name:'solar:play-bold',size:16}),'미리보기'),h(Button,{size:'sm'},'적용하기')),
  h('div',{className:'builder'},h('div',null,h(Card,{title:'블록'},h('div',{className:'stack',style:{gap:8}},[['eva:calendar-fill','학원·수업'],['solar:target-bold','미션'],['solar:clock-circle-bold','자유 시간'],['solar:moon-bold','잠자기 모드']].map(([ic,l])=>h('div',{key:l,className:'pal',draggable:true},h(Icon,{name:ic,size:20}),l))))),
   h(Card,{title:'이번 주'},h('div',{className:'stack',role:'listbox','aria-label':'일정 블록'},blocks.length?blocks.map(([id,c,ic,l,t],i)=>h(F,{key:id},s==='dragging'&&i===1&&h('div',{className:'drop on'},'여기에 놓기'),h('div',{className:'block',role:'option','aria-selected':sel===id,'data-dragging':s==='dragging'&&id==='b3'?'':undefined,tabIndex:0},h('span',{className:'tile '+c},h(Icon,{name:ic,size:20})),h('div',{className:'stack',style:{gap:2,flex:1}},h('b',null,l),h('span',{className:'muted cap'},t)),h(Icon,{name:'eva:more-horizontal-fill',size:20})))):h('div',{className:'drop',style:{minHeight:220}},'왼쪽 블록을 끌어 놓거나',h(Button,{variant:'text',size:'sm'},'지난주 일정 불러오기')))),
   h('div',{className:'props'},h(Card,{title:'속성'},sel?h('div',{className:'stack g16'},h(TextField,{label:'이름',defaultValue:'줄넘기 미션'}),h(Select,{label:'요일',defaultValue:'fri'},h('option',{value:'fri'},'금요일'),h('option',null,'토요일')),h(TextField,{label:'시작 시간',type:'time',defaultValue:'16:30'}),h(Switch,{label:'매주 반복',defaultChecked:true})):h('p',{className:'muted'},s==='empty'?'블록을 추가하면 속성이 보여요.':'블록을 선택하세요.')))));}};
S.modal={label:'Modal',states:['dialog','confirm','pending','error'],render(s){
 const bg=h('div',{className:'ghost','aria-hidden':'true'},h(Table,{caption:'미션 목록',columns:mCols(true),rows:missions.slice(0,5),rowKey:r=>r.id,minWidth:320}));
 const d=s==='dialog'?h(Dialog,{inline:true,title:'새 미션 만들기',description:'이름과 마감만 정하면 바로 보낼 수 있어요.',footer:h(F,null,h(Button,{variant:'secondary'},'취소'),h(Button,null,'보내기'))},h('div',{className:'stack g16'},h(TextField,{label:'미션 이름',required:true,placeholder:'예: 줄넘기 100번'}),h(Select,{label:'자녀'},kids.map(k=>h('option',{key:k},k))),h(Textarea,{label:'메모',rows:2}))):
  h(AlertDialog,{inline:true,danger:s!=='error',title:s==='error'?'미션을 보관할까요?':'미션 3개를 삭제할까요?',description:s==='error'?'보관함에서 다시 꺼낼 수 있어요.':'삭제한 미션과 인증 사진은 되돌릴 수 없어요.',confirmLabel:s==='error'?'보관':'삭제',errorMessage:'보관하지 못했어요. 잠시 후 다시 시도해 주세요.',previewState:s==='pending'?'pending':s==='error'?'error':undefined,onConfirm(){}});
 return h(Shell,{active:'table',title:'미션',hero:'미션 목록',sub:'12개 · 이번 주',state:s},bg,h('div',{className:'zem-stage',style:{position:'fixed',inset:0,zIndex:60,borderRadius:0,background:'transparent'}},d));}};
S.empty={label:'Empty',states:['first-run','no-results','no-access'],render(s){
 const m={'first-run':['solar:smartphone-bold','자녀 기기를 연결해 주세요','자녀 휴대폰에서 초대 코드를 입력하면 일정·미션·사용 시간을 함께 볼 수 있어요.',h(F,null,h(Button,null,'초대 코드 만들기'),h(Button,{variant:'secondary'},'연결 방법 보기')),'환영해요!','먼저 자녀 기기를 연결해요'],
  'no-results':['eva:search-fill','“수영장” 검색 결과가 없어요','철자를 확인하거나 다른 말로 찾아보세요. 보관한 미션은 검색되지 않아요.',h(Button,{variant:'secondary'},'검색 초기화'),'미션','검색 결과'],
  'no-access':['solar:shield-warning-bold','보호자 권한이 필요해요','이 기능은 대표 보호자만 쓸 수 있어요. 대표 보호자에게 권한을 요청하세요.',h(Button,{variant:'secondary'},'권한 요청'),'가족 관리','권한 없음']}[s];
 return h(Shell,{active:'dashboard',title:m[4],hero:m[5],state:s},Empty(m[0],m[1],m[2],m[3]));}};
window.ZEM_PATTERNS=S;window.ZEM_SHELL={Shell,Row,Done,Empty,Err,SkCard,Bars,Legend,miss,pt,missions};
window.ZEM_mountPattern=function(el,p,s){const def=S[p]||S.dashboard;const st=def.states.includes(s)?s:def.states[0];document.title='ZEM_V1 · '+def.label+' · '+st;ReactDOM.createRoot(el).render(h(()=>def.render(st)));return {p:S[p]?p:'dashboard',s:st}};
})();
